# requirements.txt:
# fastapi
# uvicorn
# python-dotenv
# openai
# httpx
# openpyxl
# PyMuPDF

"""
Unified App Server — auto-generated by TurboUIGen.
Provides:
  - SQLite database from schema.sql + seed.sql
  - Auto-REST endpoints for every table (GET list, GET by id, GET aggregate)
  - /api/metadata — API catalog for discoverability
  - /api/chat — LLM-powered data chat using API metadata awareness
  - Static file serving (production mode)
"""

import json
import math
import os
import re
import sqlite3
import ssl
import tempfile
from pathlib import Path
from typing import Any

import httpx
import uvicorn
from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, Query, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

load_dotenv(Path(".") / ".env")

# --- Configuration ---
DB_PATH = os.getenv("DB_PATH", "data.db")
LITELLM_API_BASE = os.getenv("LITELLM_API_BASE", "")
LITELLM_API_KEY = os.getenv("LITELLM_API_KEY", "")
LITELLM_SSL_CERT = os.getenv("LITELLM_SSL_CERT", "")
LITELLM_TIMEOUT = int(os.getenv("LITELLM_TIMEOUT", "180"))
LITELLM_MODEL = os.getenv("LITELLM_MODEL", "claude-sonnet-4-6")
API_PORT = int(os.getenv("API_PORT", "8080"))

# AWS Bedrock fallback for /api/chat — LiteLLM outages (e.g. weekend QA
# downtime) shouldn't take the whole chat feature down.
BEDROCK_MODEL_ID = os.getenv(
    "BEDROCK_MODEL_ID",
    "arn:aws:bedrock:us-east-1:992382856886:application-inference-profile/oonx9pzz8l4h",
)
BEDROCK_REGION = os.getenv("AWS_REGION", "us-east-1")
BEDROCK_PROFILE = os.getenv("AWS_PROFILE", "default")
BEDROCK_TIMEOUT = int(os.getenv("BEDROCK_TIMEOUT", "120"))

# The MCP server (mcp_server.py, mounted at /mcp below) talks only to
# DATA_API_BASE's REST API — never a direct DB connection. In this pure-Python
# deployment there's no separate data backend, so it defaults to this same
# process's own port; must be set BEFORE importing mcp_server, which reads it
# at import time.
os.environ.setdefault("DATA_API_BASE", f"http://localhost:{API_PORT}")
from mcp_server import mcp_asgi_app  # noqa: E402


# --- SSL + LLM Client setup ---
def _make_ssl_context() -> ssl.SSLContext | bool:
    if not LITELLM_SSL_CERT:
        return True
    ctx = ssl.create_default_context()
    cert_content = LITELLM_SSL_CERT.replace("\\n", "\n")
    ctx.load_verify_locations(cadata=cert_content)
    return ctx


def _make_http_client():
    return httpx.AsyncClient(
        verify=_make_ssl_context(),
        timeout=httpx.Timeout(connect=30.0, read=float(LITELLM_TIMEOUT), write=60.0, pool=30.0),
        limits=httpx.Limits(max_connections=20, max_keepalive_connections=5, keepalive_expiry=30),
    )

http_client = _make_http_client()

llm_client = None
if LITELLM_API_BASE:
    from openai import AsyncOpenAI
    base_url = LITELLM_API_BASE.rstrip("/") + "/v1"
    llm_client = AsyncOpenAI(
        api_key=LITELLM_API_KEY,
        base_url=base_url,
        http_client=http_client,
        timeout=LITELLM_TIMEOUT,
    )

# Bedrock fallback client — lazy-init (constructing it touches AWS credential
# resolution, which we don't want to pay for on every startup when LiteLLM is
# healthy and Bedrock is never actually needed).
_bedrock_client = None
# Sticky, module-level: once LiteLLM has failed enough to trigger fallback,
# every subsequent /api/chat request in this process goes straight to Bedrock
# instead of wasting retries re-checking a proxy that's known to be down.
_chat_using_fallback = False


def _get_bedrock_chat_client():
    global _bedrock_client
    if _bedrock_client is None:
        from anthropic import AsyncAnthropicBedrock
        _bedrock_client = AsyncAnthropicBedrock(
            aws_profile=BEDROCK_PROFILE,
            aws_region=BEDROCK_REGION,
            http_client=httpx.AsyncClient(
                verify=_make_ssl_context(),
                timeout=httpx.Timeout(connect=30.0, read=float(BEDROCK_TIMEOUT), write=60.0, pool=30.0),
            ),
        )
    return _bedrock_client


def _openai_tools_to_anthropic(tools_openai: list[dict]) -> list[dict]:
    """MCP tools are fetched once as OpenAI-style function-calling schemas
    (see _get_chat_tools) since that's the primary LiteLLM/OpenAI-SDK path.
    Bedrock's native tool-use format is structurally the same information,
    just renamed/flattened — no MCP round-trip needed to reshape it."""
    return [
        {
            "name": t["function"]["name"],
            "description": t["function"].get("description", ""),
            "input_schema": t["function"].get("parameters", {"type": "object", "properties": {}}),
        }
        for t in tools_openai
    ]


async def _run_bedrock_chat_stream(system_prompt: str, conversation: list[dict], tools_openai: list[dict],
                                    max_tool_rounds: int = 5):
    """Anthropic-native tool-use loop for the Bedrock fallback path — kept
    separate from the OpenAI-SDK loop below since the two providers' tool-
    calling wire formats are genuinely different shapes.

    An async generator rather than a plain coroutine so the caller can stream
    "tool_call" progress events to the frontend as they happen instead of just
    showing a blank spinner for the whole multi-round turn. Yields
    {"type": "tool_call", ...} as each tool starts, then exactly one
    {"type": "final_text", "text": ...} at the end."""
    client_bedrock = _get_bedrock_chat_client()
    anthropic_tools = _openai_tools_to_anthropic(tools_openai)
    messages: list[dict] = list(conversation)

    for _round in range(max_tool_rounds):
        response = await client_bedrock.messages.create(
            model=BEDROCK_MODEL_ID,
            max_tokens=4096,
            system=system_prompt,
            messages=messages,
            tools=anthropic_tools,
        )

        if response.stop_reason != "tool_use":
            yield {"type": "final_text", "text": "".join(b.text for b in response.content if b.type == "text")}
            return

        tool_use_blocks = [b for b in response.content if b.type == "tool_use"]
        if not tool_use_blocks:
            yield {"type": "final_text", "text": "".join(b.text for b in response.content if b.type == "text")}
            return

        messages.append({"role": "assistant", "content": response.content})
        tool_results = []
        for block in tool_use_blocks:
            print(f"[chat] Bedrock tool call: {block.name}({json.dumps(block.input, default=str)[:200]})", flush=True)
            yield {"type": "tool_call", "tool": block.name, "args": block.input}
            result = await _execute_chat_tool(block.name, block.input)
            tool_results.append({"type": "tool_result", "tool_use_id": block.id, "content": result})
        messages.append({"role": "user", "content": tool_results})

    yield {
        "type": "final_text",
        "text": "".join(b.text for b in response.content if b.type == "text")
        or "I wasn't able to complete the analysis in the allowed steps.",
    }


# --- Database ---
def _get_db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def _init_db():
    """Initialize database from schema.sql and seed.sql if they exist.

    Supports incremental refinement: if database already has tables, only
    CREATE IF NOT EXISTS and seed NEW tables (those that are empty).
    """
    conn = _get_db()
    schema_file = Path("schema.sql")
    seed_file = Path("seed.sql")

    if schema_file.exists():
        existing_tables = {r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
        ).fetchall()}

        if not existing_tables:
            conn.executescript(schema_file.read_text(encoding="utf-8"))
            print(f"[db] Executed schema.sql (new database)")
        else:
            # Incremental: run schema with IF NOT EXISTS to add new tables
            schema_sql = schema_file.read_text(encoding="utf-8")
            # Inject IF NOT EXISTS into CREATE TABLE statements that lack it
            import re as _re
            schema_sql = _re.sub(
                r"CREATE\s+TABLE\s+(?!IF\s+NOT\s+EXISTS)",
                "CREATE TABLE IF NOT EXISTS ",
                schema_sql,
                flags=_re.IGNORECASE,
            )
            try:
                conn.executescript(schema_sql)
                new_tables = {r[0] for r in conn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
                ).fetchall()} - existing_tables
                if new_tables:
                    print(f"[db] Added new tables: {', '.join(sorted(new_tables))}")
                else:
                    print(f"[db] Schema up to date ({len(existing_tables)} tables)")
            except Exception as e:
                print(f"[db] Schema update warning: {e}")

    if seed_file.exists():
        tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").fetchall()
        # Seed tables that are empty (supports adding data to new tables during refinement)
        empty_tables = set()
        for (table_name,) in tables:
            count = conn.execute(f"SELECT COUNT(*) FROM [{table_name}]").fetchone()[0]
            if count == 0:
                empty_tables.add(table_name)

        if empty_tables:
            # Extract and run INSERT statements for empty tables only
            seed_sql = seed_file.read_text(encoding="utf-8")
            import re as _re
            # Replace literal 'null' in VALUES with empty string to avoid NOT NULL violations
            seed_sql = _re.sub(r",null([,)])", r",''\\1", seed_sql, flags=_re.IGNORECASE)
            seed_sql = _re.sub(r"\(null,", "('',", seed_sql, flags=_re.IGNORECASE)
            # Split on INSERT INTO to process per-table
            statements = _re.split(r"(?=INSERT\s+INTO)", seed_sql, flags=_re.IGNORECASE)
            seeded = []
            for stmt in statements:
                stmt = stmt.strip()
                if not stmt:
                    continue
                # Find target table name
                m = _re.match(r"INSERT\s+INTO\s+[`\"]?(\w+)[`\"]?", stmt, _re.IGNORECASE)
                if m and m.group(1) in empty_tables:
                    try:
                        conn.executescript(stmt)
                        seeded.append(m.group(1))
                    except Exception as e:
                        # Retry with OR IGNORE to skip constraint-violating rows
                        try:
                            stmt_ignore = _re.sub(
                                r"INSERT\s+INTO",
                                "INSERT OR IGNORE INTO",
                                stmt,
                                flags=_re.IGNORECASE,
                            )
                            conn.executescript(stmt_ignore)
                            seeded.append(m.group(1))
                            print(f"[db] Seeded {m.group(1)} with OR IGNORE (some rows skipped)")
                        except Exception as e2:
                            print(f"[db] Seed warning for {m.group(1)}: {e2}")
                elif not m:
                    # Non-INSERT preamble (pragmas, etc.) — run unconditionally
                    try:
                        conn.executescript(stmt)
                    except Exception:
                        pass
            if seeded:
                print(f"[db] Seeded new tables: {', '.join(sorted(set(seeded)))}")
            else:
                print(f"[db] No empty tables to seed")
        else:
            print(f"[db] Skipped seed.sql (all tables have data)")

    _apply_versioned_migrations(conn)
    conn.close()


def _apply_versioned_migrations(conn: sqlite3.Connection):
    """Apply schema_v2.sql/seed_v2.sql (etc.) pairs from a refine's
    incremental DB delta — see CrewOrchestrator._run_data_modeling_refine.
    Unlike v1's schema.sql above (safe to re-run every startup via CREATE
    TABLE IF NOT EXISTS), these can contain ALTER TABLE ADD COLUMN, which
    SQLite errors on if run twice — so each version is tracked in
    _schema_migrations and applied exactly once, ever.
    """
    import re as _re

    conn.execute(
        "CREATE TABLE IF NOT EXISTS _schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT)"
    )
    conn.commit()
    applied = {r[0] for r in conn.execute("SELECT version FROM _schema_migrations").fetchall()}

    versions = sorted(
        int(m.group(1)) for f in Path(".").glob("schema_v*.sql")
        for m in [_re.match(r"schema_v(\d+)\.sql$", f.name)] if m
    )
    for version in versions:
        if version in applied:
            continue
        schema_file = Path(f"schema_v{version}.sql")
        seed_file = Path(f"seed_v{version}.sql")
        try:
            conn.executescript(schema_file.read_text(encoding="utf-8"))
            if seed_file.exists():
                seed_sql = seed_file.read_text(encoding="utf-8")
                seed_sql = _re.sub(r",null([,)])", r",''\1", seed_sql, flags=_re.IGNORECASE)
                seed_sql = _re.sub(r"\(null,", "('',", seed_sql, flags=_re.IGNORECASE)
                conn.executescript(seed_sql)
            conn.execute(
                "INSERT INTO _schema_migrations (version, applied_at) VALUES (?, datetime('now'))",
                (version,),
            )
            conn.commit()
            print(f"[db] Applied migration v{version} (schema_v{version}.sql" +
                  (f" + seed_v{version}.sql" if seed_file.exists() else "") + ")")
        except Exception as e:
            print(f"[db] Migration v{version} failed, will retry next startup: {e}")


def _get_tables() -> list[str]:
    conn = _get_db()
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
    ).fetchall()
    conn.close()
    return [r["name"] for r in rows]


def _get_table_schema(table: str) -> list[dict]:
    conn = _get_db()
    rows = conn.execute(f"PRAGMA table_info('{table}')").fetchall()
    conn.close()
    return [{"name": r["name"], "type": r["type"], "pk": bool(r["pk"]), "nullable": not r["notnull"]} for r in rows]


def _get_table_count(table: str) -> int:
    conn = _get_db()
    count = conn.execute(f"SELECT COUNT(*) as c FROM [{table}]").fetchone()["c"]
    conn.close()
    return count


# --- App ---
# Combined lifespan, not just lifespan=mcp_asgi_app.lifespan directly: this file
# used to run its startup logic (_init_db, _build_metadata) via the older
# @app.on_event("startup") decorator. Passing an explicit `lifespan=` to
# FastAPI() alongside that decorator does NOT reliably run both — verified by
# testing: the app started and /mcp worked fine, but _init_db() silently never
# ran (every table came back empty). Wrapping the original startup logic
# inside one explicit async-context-manager lifespan — which also enters the
# MCP sub-app's own lifespan (required for its session manager to start; a
# bare app.mount() without this produces a mount that accepts connections but
# terminates every session) — is unambiguous and doesn't depend on how a given
# FastAPI version reconciles the two older/newer mechanisms.
from contextlib import asynccontextmanager as _asynccontextmanager


@_asynccontextmanager
async def _lifespan(_app: FastAPI):
    async with mcp_asgi_app.lifespan(_app):
        _init_db()
        _build_metadata()
        tables = _get_tables()
        print(f"\n  TurboUI App Server running on port {API_PORT}")
        print(f"  Database: {DB_PATH} ({len(tables)} tables)")
        print(f"  Endpoints:")
        for meta in _api_metadata:
            print(f"    GET /api/data/{meta['table']}  ({meta['rowCount']} rows)")
        print(f"    GET  /api/metadata        — API catalog")
        print(f"    POST /api/chat            — AI data chat")
        print(f"    GET  /mcp                 — MCP server (tools for /api/chat)")
        print(f"    GET  /health              — Health check\n")
        yield


app = FastAPI(title="TurboUI App Server", lifespan=_lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_origin_regex=r"http://(localhost|127\.0\.0\.1)(:\d+)?",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
# Mounted before any other routes (esp. the SPA catch-all near the end of this
# file) so /mcp/* is matched first.
app.mount("/mcp", mcp_asgi_app)


# --- API Metadata ---
_api_metadata: list[dict] = []


def _build_metadata():
    """Build API metadata from discovered tables."""
    global _api_metadata
    _api_metadata = []
    tables = _get_tables()
    for table in tables:
        schema = _get_table_schema(table)
        count = _get_table_count(table)
        columns = [col["name"] for col in schema]
        numeric_cols = [col["name"] for col in schema if col["type"].upper() in ("INTEGER", "REAL", "NUMERIC", "FLOAT", "DOUBLE")]

        _api_metadata.append({
            "table": table,
            "description": f"Data table '{table}' with {count} rows",
            "rowCount": count,
            "columns": schema,
            "endpoints": {
                "list": f"/api/data/{table}",
                "byId": f"/api/data/{table}/{{id}}",
                "aggregate": f"/api/data/{table}/aggregate",
                "create": f"/api/data/{table}",
                "update": f"/api/data/{table}/{{id}}",
                "delete": f"/api/data/{table}/{{id}}",
            },
            "queryParams": {
                "list": {
                    "limit": "number (default 100, max 1000)",
                    "offset": "number (default 0)",
                    "sort": f"column name ({', '.join(columns[:5])}...)",
                    "order": "asc|desc (default asc)",
                    "filter": "column:operator:value (operators: eq,ne,gt,lt,gte,lte,like,in)",
                },
                "aggregate": {
                    "groupBy": f"column name ({', '.join(columns[:5])}...)",
                    "metric": f"sum|avg|min|max|count",
                    "column": f"numeric column ({', '.join(numeric_cols[:3])}...)",
                    "filter": "same as list",
                },
            },
        })


@app.get("/api/metadata")
async def get_metadata():
    return {"tables": _api_metadata, "chatEndpoint": "/api/chat"}


# --- Generic Data Endpoints ---
def _parse_filter(filter_str: str) -> tuple[str, list]:
    """Parse 'column:operator:value' into SQL WHERE clause."""
    parts = filter_str.split(":", 2)
    if len(parts) != 3:
        return "", []
    col, op, val = parts
    col_safe = re.sub(r"[^a-zA-Z0-9_]", "", col)
    ops = {"eq": "=", "ne": "!=", "gt": ">", "lt": "<", "gte": ">=", "lte": "<=", "like": "LIKE"}
    if op == "in":
        values = val.split(",")
        placeholders = ",".join("?" * len(values))
        return f"[{col_safe}] IN ({placeholders})", values
    if op not in ops:
        return "", []
    sql_op = ops[op]
    if op == "like":
        val = f"%{val}%"
    return f"[{col_safe}] {sql_op} ?", [val]


@app.get("/api/data/{table}")
async def get_table_data(
    table: str,
    limit: int = Query(100, ge=1, le=1000),
    offset: int = Query(0, ge=0),
    sort: str | None = None,
    order: str = Query("asc", regex="^(asc|desc)$"),
    filter: str | None = None,
):
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    conn = _get_db()
    where_clause = ""
    params: list = []

    if filter:
        filters = filter.split(";")
        conditions = []
        for f in filters:
            clause, vals = _parse_filter(f)
            if clause:
                conditions.append(clause)
                params.extend(vals)
        if conditions:
            where_clause = "WHERE " + " AND ".join(conditions)

    count_sql = f"SELECT COUNT(*) as c FROM [{table}] {where_clause}"
    total = conn.execute(count_sql, params).fetchone()["c"]

    sort_clause = ""
    if sort:
        sort_safe = re.sub(r"[^a-zA-Z0-9_]", "", sort)
        sort_clause = f"ORDER BY [{sort_safe}] {order.upper()}"

    query = f"SELECT * FROM [{table}] {where_clause} {sort_clause} LIMIT ? OFFSET ?"
    rows = conn.execute(query, params + [limit, offset]).fetchall()
    conn.close()

    data = [dict(r) for r in rows]
    return {
        "data": data,
        "total": total,
        "limit": limit,
        "offset": offset,
        "hasMore": (offset + limit) < total,
    }


# NOTE: /aggregate must be registered BEFORE /{row_id} — Starlette matches
# routes in registration order, and the literal "aggregate" segment would
# otherwise be captured by {row_id}, failing int-parsing validation before
# ever reaching this handler (confirmed live: GET /api/data/sales/aggregate
# 422'd with "unable to parse 'aggregate' as an integer" until this was
# reordered). Previously masked because nothing called this endpoint over
# HTTP — the old chat-tool code queried the DB directly instead.
@app.get("/api/data/{table}/aggregate")
async def get_table_aggregate(
    table: str,
    groupBy: str | None = None,
    metric: str = Query("count", regex="^(sum|avg|min|max|count)$"),
    column: str | None = None,
    filter: str | None = None,
    limit: int = Query(50, ge=1, le=200),
):
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    where_clause = ""
    params: list = []
    if filter:
        filters = filter.split(";")
        conditions = []
        for f in filters:
            clause, vals = _parse_filter(f)
            if clause:
                conditions.append(clause)
                params.extend(vals)
        if conditions:
            where_clause = "WHERE " + " AND ".join(conditions)

    if metric == "count":
        agg_expr = "COUNT(*)"
    else:
        if not column:
            raise HTTPException(status_code=400, detail=f"'column' required for metric '{metric}'")
        col_safe = re.sub(r"[^a-zA-Z0-9_]", "", column)
        agg_expr = f"{metric.upper()}([{col_safe}])"

    conn = _get_db()
    if groupBy:
        group_safe = re.sub(r"[^a-zA-Z0-9_]", "", groupBy)
        query = f"SELECT [{group_safe}] as _group, {agg_expr} as _value FROM [{table}] {where_clause} GROUP BY [{group_safe}] ORDER BY _value DESC LIMIT ?"
        rows = conn.execute(query, params + [limit]).fetchall()
        conn.close()
        return {"data": [{"group": r["_group"], "value": r["_value"]} for r in rows]}
    else:
        query = f"SELECT {agg_expr} as _value FROM [{table}] {where_clause}"
        row = conn.execute(query, params).fetchone()
        conn.close()
        return {"value": row["_value"]}


@app.get("/api/data/{table}/{row_id}")
async def get_table_row(table: str, row_id: int):
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    conn = _get_db()
    row = conn.execute(f"SELECT * FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
    conn.close()

    if not row:
        raise HTTPException(status_code=404, detail="Row not found")
    return dict(row)


# --- Generic CRUD (Create / Update / Delete) Endpoints ---

@app.post("/api/data/{table}")
async def create_row(table: str, request: Request):
    """Insert a new row into a table. Body: JSON object with column:value pairs."""
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    body = await request.json()
    if not body or not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="Request body must be a JSON object")

    # Validate columns exist
    schema = _get_table_schema(table)
    valid_cols = {col["name"] for col in schema}
    cols = [k for k in body.keys() if k in valid_cols]
    if not cols:
        raise HTTPException(status_code=400, detail="No valid columns provided")

    values = [body[c] for c in cols]
    placeholders = ", ".join("?" * len(cols))
    col_list = ", ".join(f"[{c}]" for c in cols)

    conn = _get_db()
    try:
        cursor = conn.execute(f"INSERT INTO [{table}] ({col_list}) VALUES ({placeholders})", values)
        conn.commit()
        row_id = cursor.lastrowid
        row = conn.execute(f"SELECT *, rowid FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
        conn.close()
        return {"data": dict(row), "id": row_id}
    except sqlite3.IntegrityError as e:
        conn.close()
        raise HTTPException(status_code=409, detail=str(e))
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=500, detail=str(e))


@app.put("/api/data/{table}/{row_id}")
async def update_row(table: str, row_id: int, request: Request):
    """Update an existing row. Body: JSON object with column:value pairs to update."""
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    body = await request.json()
    if not body or not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="Request body must be a JSON object")

    schema = _get_table_schema(table)
    valid_cols = {col["name"] for col in schema}
    cols = [k for k in body.keys() if k in valid_cols]
    if not cols:
        raise HTTPException(status_code=400, detail="No valid columns provided")

    set_clause = ", ".join(f"[{c}] = ?" for c in cols)
    values = [body[c] for c in cols]

    conn = _get_db()
    # Check row exists
    existing = conn.execute(f"SELECT rowid FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
    if not existing:
        conn.close()
        raise HTTPException(status_code=404, detail="Row not found")

    try:
        conn.execute(f"UPDATE [{table}] SET {set_clause} WHERE rowid = ?", values + [row_id])
        conn.commit()
        row = conn.execute(f"SELECT *, rowid FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
        conn.close()
        return {"data": dict(row)}
    except sqlite3.IntegrityError as e:
        conn.close()
        raise HTTPException(status_code=409, detail=str(e))
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=500, detail=str(e))


@app.delete("/api/data/{table}/{row_id}")
async def delete_row(table: str, row_id: int):
    """Delete a row by rowid."""
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    conn = _get_db()
    existing = conn.execute(f"SELECT rowid FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
    if not existing:
        conn.close()
        raise HTTPException(status_code=404, detail="Row not found")

    conn.execute(f"DELETE FROM [{table}] WHERE rowid = ?", [row_id])
    conn.commit()
    conn.close()
    return {"deleted": True, "id": row_id}


# --- Chat Endpoint ---
class ChatMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    responseFormat: str = "auto"
    context: dict | None = None


def _build_chat_system_prompt(response_format: str = "auto") -> str:
    """Build a system prompt. Data access happens through tool calls, not the prompt."""
    prompt = (
        "You are an expert data analyst for this application.\n\n"
        "You have access to MCP tools that let you query the live database. "
        "ALWAYS use tools to fetch real data before answering data questions. "
        "Never guess or fabricate numbers — call the appropriate get_ or aggregate_ tool. "
        "If unsure which table/column to use, call get_api_metadata first.\n"
    )
    if response_format == "chart":
        prompt += (
            "\n\nIMPORTANT: Respond with a chart. After fetching data, output ONLY valid JSON: "
            '{"type": "bar"|"line"|"donut"|"scatter", "title": "...", "data": [...], "xKey": "fieldName", "yKeys": ["fieldName1"]}'
        )
    elif response_format == "table":
        prompt += "\n\nIMPORTANT: Respond with tabular output as a JSON array of objects."
    elif response_format == "auto":
        prompt += (
            "\n\nResponse format rules:\n"
            "- Chart: wrap in ```chart\\n{json}\\n``` with {type, title, data, xKey, yKeys}\n"
            "- Map: wrap in ```map\\n{json}\\n``` with {mapType: world|usa, title, data: [{id, value, label}], valueLabel, colorScheme}\n"
            "- Table: wrap in ```table\\n[{...}]\\n```\n"
            "- Otherwise: plain text with markdown\n"
            "- ALWAYS base answers on actual tool call results, not assumptions."
        )
    return prompt


from fastmcp import Client as _MCPClient

_MCP_SELF_URL = f"http://localhost:{API_PORT}/mcp"
_mcp_client: _MCPClient | None = None
_mcp_tools_openai: list[dict] | None = None


async def _get_mcp_client() -> _MCPClient:
    """Lazily connect to this same process's own /mcp mount, reused across
    requests. Lazy (not connected at module-import time or in the startup
    hook) because there's no running event loop until a request handler
    actually runs — matches this codebase's existing precedent of lazy,
    cached discovery on first chat request."""
    global _mcp_client
    if _mcp_client is None or not _mcp_client.is_connected():
        _mcp_client = _MCPClient(_MCP_SELF_URL)
        await _mcp_client.__aenter__()
    return _mcp_client


async def _get_chat_tools() -> list[dict]:
    """Fetch tools from the real MCP server (mounted at /mcp on this same
    process) once, converted to OpenAI function-calling format. MCP tool
    schemas are already JSON-Schema, so this is a straight field mapping."""
    global _mcp_tools_openai
    if _mcp_tools_openai is None:
        client = await _get_mcp_client()
        mcp_tools = await client.list_tools()
        _mcp_tools_openai = [
            {
                "type": "function",
                "function": {
                    "name": t.name,
                    "description": t.description or "",
                    "parameters": t.inputSchema,
                },
            }
            for t in mcp_tools
        ]
    return _mcp_tools_openai


async def _execute_chat_tool(name: str, args: dict) -> str:
    """Execute a tool call via the real MCP server instead of querying the
    local DB directly — the query logic itself now lives in mcp_server.py so
    it's shared with the Java-backend sidecar deployment of this same tool
    server."""
    try:
        client = await _get_mcp_client()
        result = await client.call_tool(name, args)
        data = result.data if hasattr(result, "data") else result
        return data if isinstance(data, str) else json.dumps(data, default=str)
    except Exception as e:
        return json.dumps({"error": f"Tool execution failed: {str(e)}"})


def _parse_llm_response(text: str) -> dict[str, Any]:
    """Parse LLM response for embedded chart/table/map blocks."""
    map_match = re.search(r"```map\s*\n([\s\S]*?)\n```", text)
    if map_match:
        try:
            data = json.loads(map_match.group(1))
            clean = text[:map_match.start()].strip() + "\n\n" + text[map_match.end():].strip()
            return {"response": clean.strip(), "type": "map", "data": data}
        except json.JSONDecodeError:
            pass

    chart_match = re.search(r"```chart\s*\n([\s\S]*?)\n```", text)
    if chart_match:
        try:
            data = json.loads(chart_match.group(1))
            clean = text[:chart_match.start()].strip() + "\n\n" + text[chart_match.end():].strip()
            return {"response": clean.strip(), "type": "chart", "data": data}
        except json.JSONDecodeError:
            pass

    table_match = re.search(r"```table\s*\n([\s\S]*?)\n```", text)
    if table_match:
        try:
            data = json.loads(table_match.group(1))
            clean = text[:table_match.start()].strip() + "\n\n" + text[table_match.end():].strip()
            return {"response": clean.strip(), "type": "table", "data": data}
        except json.JSONDecodeError:
            pass

    try:
        data = json.loads(text)
        if isinstance(data, dict) and "type" in data:
            return {"response": text, "type": "chart", "data": data}
        if isinstance(data, list):
            return {"response": text, "type": "table", "data": data}
    except json.JSONDecodeError:
        pass

    return {"response": text, "type": "text", "data": None}


async def _run_litellm_chat_stream(loop_messages: list[dict], tools: list[dict], max_rounds: int = 5):
    """OpenAI-SDK tool-use loop against LiteLLM. `loop_messages` is mutated in
    place as rounds progress — same as the previous non-streaming version,
    just yielding "tool_call" progress events instead of only returning text."""
    global llm_client
    for _round in range(max_rounds):
        completion = await llm_client.chat.completions.create(
            model=LITELLM_MODEL,
            messages=loop_messages,
            tools=tools,
            temperature=0.3,
        )
        choice = completion.choices[0]

        if choice.finish_reason == "tool_calls" or (choice.message.tool_calls and len(choice.message.tool_calls) > 0):
            loop_messages.append(choice.message)
            for tc in choice.message.tool_calls:
                fn_name = tc.function.name
                fn_args = json.loads(tc.function.arguments) if tc.function.arguments else {}
                print(f"[chat] Tool call: {fn_name}({json.dumps(fn_args)})", flush=True)
                yield {"type": "tool_call", "tool": fn_name, "args": fn_args}
                result = await _execute_chat_tool(fn_name, fn_args)
                loop_messages.append({"role": "tool", "tool_call_id": tc.id, "content": result})
        else:
            yield {"type": "final_text", "text": choice.message.content or ""}
            return

    # Max rounds exhausted — one more plain call for whatever answer we can get
    final = await llm_client.chat.completions.create(
        model=LITELLM_MODEL,
        messages=loop_messages,
        temperature=0.3,
    )
    yield {"type": "final_text", "text": final.choices[0].message.content or ""}


def _sse(event: dict) -> str:
    return f"data: {json.dumps(event, default=str)}\n\n"


async def _stream_chat_events(request: "ChatRequest"):
    """
    Drives the whole /api/chat turn as a stream of SSE events instead of one
    blocking JSON response, so the frontend can show real per-tool-call
    progress instead of a blank spinner for the whole multi-round turn.
    Event types: tool_call, status (provider retry/fallback), final (the
    parse result), error (terminal failure — once streaming has started, a
    real HTTPException can no longer be raised, so failures become events).
    """
    import asyncio
    from openai import AsyncOpenAI
    global llm_client, http_client, _chat_using_fallback

    system_prompt = _build_chat_system_prompt(response_format=request.responseFormat or "auto")
    if request.context:
        system_prompt += f"\n\nAdditional context: {json.dumps(request.context)}"

    recent = request.messages[-20:] if len(request.messages) > 20 else request.messages
    conversation = [{"role": m.role, "content": m.content} for m in recent]
    tools = await _get_chat_tools()
    max_rounds = 5

    # Sticky fallback: LiteLLM already known to be down this session — skip
    # straight to Bedrock instead of wasting more retries against it.
    if _chat_using_fallback:
        try:
            final_text = None
            async for evt in _run_bedrock_chat_stream(system_prompt, conversation, tools, max_rounds):
                if evt["type"] == "final_text":
                    final_text = evt["text"]
                else:
                    yield _sse(evt)
            yield _sse({"type": "final", "result": _parse_llm_response(final_text or "")})
        except Exception as e:
            yield _sse({"type": "error", "detail": f"Bedrock call failed: {e}"})
        return

    messages = [{"role": "system", "content": system_prompt}] + conversation

    last_err = None
    for _attempt in range(3):
        try:
            loop_messages = list(messages)
            final_text = None
            async for evt in _run_litellm_chat_stream(loop_messages, tools, max_rounds):
                if evt["type"] == "final_text":
                    final_text = evt["text"]
                else:
                    yield _sse(evt)
            yield _sse({"type": "final", "result": _parse_llm_response(final_text or "")})
            return
        except Exception as attempt_err:
            last_err = attempt_err
            print(f"[chat] attempt {_attempt+1} failed: {type(attempt_err).__name__}: {attempt_err}", flush=True)
            if _attempt < 2:
                yield _sse({"type": "status", "message": "Connection hiccup — retrying..."})
                try:
                    await http_client.aclose()
                except Exception:
                    pass
                http_client = _make_http_client()
                llm_client = AsyncOpenAI(
                    api_key=LITELLM_API_KEY,
                    base_url=LITELLM_API_BASE.rstrip("/") + "/v1",
                    http_client=http_client,
                    timeout=LITELLM_TIMEOUT,
                )
                await asyncio.sleep(2 * (_attempt + 1))

    # LiteLLM exhausted all retries — fall back to Bedrock rather than
    # failing the request outright. Sticky: every subsequent /api/chat call
    # in this process goes straight to Bedrock (see the check above).
    print(
        f"\n{'='*60}\n"
        f"[CHAT FALLBACK] LiteLLM unavailable after 3 attempts.\n"
        f"                Switching to AWS Bedrock ({BEDROCK_MODEL_ID}).\n"
        f"                Last error: {last_err}\n"
        f"{'='*60}\n",
        flush=True,
    )
    yield _sse({"type": "status", "message": "Primary AI service unavailable — switching to backup..."})
    _chat_using_fallback = True
    try:
        final_text = None
        async for evt in _run_bedrock_chat_stream(system_prompt, conversation, tools, max_rounds):
            if evt["type"] == "final_text":
                final_text = evt["text"]
            else:
                yield _sse(evt)
        yield _sse({"type": "final", "result": _parse_llm_response(final_text or "")})
    except Exception as bedrock_err:
        err_msg = f"Both LiteLLM and Bedrock failed.\n  LiteLLM error: {last_err}\n  Bedrock error: {bedrock_err}"
        yield _sse({"type": "error", "detail": err_msg})


@app.post("/api/chat")
async def chat(request: ChatRequest):
    if not llm_client and not _chat_using_fallback:
        raise HTTPException(status_code=503, detail="LLM not configured — check .env credentials")
    return StreamingResponse(_stream_chat_events(request), media_type="text/event-stream")


@app.get("/api/chat/health")
async def chat_health():
    """Check LLM connectivity before user tries to chat."""
    if not LITELLM_API_BASE or not LITELLM_API_KEY:
        return {"status": "not_configured", "error": "LITELLM_API_BASE and LITELLM_API_KEY not set in .env"}
    try:
        import httpx as _httpx
        async with _httpx.AsyncClient(verify=_make_ssl_context(), timeout=10.0) as client:
            resp = await client.get(LITELLM_API_BASE.rstrip("/") + "/health")
            return {"status": "healthy", "litellm_base": LITELLM_API_BASE, "litellm_status": resp.status_code}
    except Exception as e:
        return {"status": "unreachable", "litellm_base": LITELLM_API_BASE, "error": str(e)}


# --- File upload endpoints (for Excel/PDF chat) ---
@app.post("/api/ingest/excel")
async def ingest_excel(file: UploadFile = File(...)):
    try:
        import openpyxl
        suffix = Path(file.filename or "upload.xlsx").suffix
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            content = await file.read()
            tmp.write(content)
            tmp_path = tmp.name

        wb = openpyxl.load_workbook(tmp_path, read_only=True, data_only=True)
        sheets = []
        for sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            rows_raw = list(ws.iter_rows(values_only=True))
            if not rows_raw:
                continue
            headers = [str(h) if h else f"col_{i}" for i, h in enumerate(rows_raw[0])]
            data_rows = [dict(zip(headers, row)) for row in rows_raw[1:]]
            schema = [{"name": h, "type": _detect_col_type([r.get(h) for r in data_rows[:50]])} for h in headers]
            sheets.append({
                "name": sheet_name,
                "schema": schema,
                "rows": data_rows[:100],
                "totalRows": len(data_rows),
                "sampleRows": data_rows[:10],
            })
        wb.close()
        os.unlink(tmp_path)
        return {"sheets": sheets}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/ingest/pdf")
async def ingest_pdf(file: UploadFile = File(...)):
    try:
        import fitz
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
            content = await file.read()
            tmp.write(content)
            tmp_path = tmp.name

        doc = fitz.open(tmp_path)
        chunks = [page.get_text() for page in doc]
        full_text = "\n".join(chunks)
        title = doc.metadata.get("title", "") if doc.metadata else ""
        page_count = len(doc)
        doc.close()
        os.unlink(tmp_path)
        return {"pages": page_count, "text": full_text, "chunks": chunks, "metadata": {"title": title, "pages": page_count}}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def _detect_col_type(values: list) -> str:
    non_empty = [v for v in values if v is not None and str(v).strip() != ""]
    if not non_empty:
        return "TEXT"
    numeric_count = sum(1 for v in non_empty if _is_numeric(v))
    if numeric_count == len(non_empty):
        return "REAL" if any("." in str(v) for v in non_empty) else "INTEGER"
    return "TEXT"


def _is_numeric(v) -> bool:
    try:
        float(v)
        return True
    except (ValueError, TypeError):
        return False


# --- Health ---
@app.get("/health")
async def health():
    tables = _get_tables()
    return {"status": "ok", "tables": len(tables), "database": DB_PATH}




# --- Static file serving (production) ---
dist_dir = Path("dist")
if dist_dir.exists():
    app.mount("/assets", StaticFiles(directory=str(dist_dir / "assets")), name="assets")

    @app.get("/{full_path:path}")
    async def serve_spa(full_path: str):
        file_path = dist_dir / full_path
        if file_path.exists() and file_path.is_file():
            return FileResponse(str(file_path))
        return FileResponse(str(dist_dir / "index.html"))


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=API_PORT)
