import { useState, useEffect, useCallback, useRef } from 'react'

interface ApiResponse<T> {
  data: T[]
  total: number
  limit: number
  offset: number
  hasMore: boolean
}

interface AggregateResponse {
  data?: { group: string; value: number }[]
  value?: number
}

interface UseApiOptions {
  limit?: number
  offset?: number
  sort?: string
  order?: 'asc' | 'desc'
  filter?: string
  autoFetch?: boolean
}

interface UseApiResult<T> {
  data: T[]
  total: number
  loading: boolean
  error: string | null
  hasMore: boolean
  refetch: () => void
  fetchMore: () => void
}

const _API_BASE = (import.meta as any).env?.BASE_URL?.replace(/\/$/, '') || ''

async function _fetchWithRetry(url: string, opts: RequestInit = {}, retries = 2): Promise<Response> {
  // A 502 is the platform's own dev proxy reporting it couldn't reach the
  // backend process AT ALL — not an application error the backend itself
  // returned. That's most often a brief window right after a fresh build
  // where the frontend is already up but a slow-booting Java/Python
  // backend hasn't finished starting yet, which is worth waiting out much
  // longer than a genuine 5xx from the app's own code (which won't
  // self-resolve no matter how many times it's retried). Reproduced
  // directly: a page 502'd once right after "ready" and stayed empty,
  // while the same endpoint worked fine seconds later — the old 2-retry/
  // ~3s budget below just wasn't enough margin for that gap.
  const maxAttemptsFor502 = 6
  let attempt = 0
  while (true) {
    try {
      const res = await fetch(url, opts)
      const cap = res.status === 502 ? maxAttemptsFor502 : retries
      if (res.status >= 500 && attempt < cap) {
        await new Promise(r => setTimeout(r, 1000 * Math.min(attempt + 1, 5)))
        attempt++
        continue
      }
      return res
    } catch (e) {
      if (attempt >= retries) throw e
      await new Promise(r => setTimeout(r, 1000 * Math.min(attempt + 1, 5)))
      attempt++
    }
  }
}

// T is the SINGLE-ROW type, not an array — `data` below is already typed T[].
// useApi<RowType>('table') is correct; useApi<RowType[]>('table') is a common
// mistake that makes `data` a RowType[][] and breaks everywhere it's used as
// a flat array.
export function useApi<T = Record<string, unknown>>(
  table: string,
  options: UseApiOptions = {}
): UseApiResult<T> {
  // 500 to match the convention used elsewhere in generated apps (ChartPanel,
  // CardGrid both hardcode limit=500) — 100 was an inconsistent outlier that
  // silently truncated pages doing full-table analysis (e.g. "find the latest
  // hour across every store") rather than paginated browsing, making stores
  // whose rows fell outside the first 100 look like they had no data at all.
  const { limit = 500, offset = 0, sort, order = 'asc', filter, autoFetch = true } = options
  const [data, setData] = useState<T[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [hasMore, setHasMore] = useState(false)
  const currentOffset = useRef(offset)
  const abortRef = useRef<AbortController | null>(null)

  const buildUrl = useCallback((off: number) => {
    const params = new URLSearchParams()
    params.set('limit', String(limit))
    params.set('offset', String(off))
    // Java controllers are generated against Spring Data's own page/size
    // convention, never this platform's limit/offset — reproduced directly:
    // every request silently capped at a Java controller's own `size`
    // default (usually 20) no matter how high `limit` was set, since the
    // Java side never saw a `size`/`page` param at all, only `limit`/
    // `offset` which it doesn't recognize and simply ignores. Send both
    // conventions on every request so either backend is satisfied — a
    // Python route ignores the extra page/size params it doesn't declare,
    // exactly as harmlessly as a Java route ignores limit/offset today.
    params.set('size', String(limit))
    params.set('page', String(Math.floor(off / Math.max(limit, 1))))
    if (sort) params.set('sort', sort)
    if (order) params.set('order', order)
    if (filter) params.set('filter', filter)
    return `${_API_BASE}/api/${table}?${params.toString()}`
  }, [table, limit, sort, order, filter])

  // Named per-entity routes generated by api_services_engineer normally
  // return the same plain {data, total, limit, offset, hasMore} shape this
  // hook has always expected — but a Java backend's own convention
  // (Spring Data's Page<T>) has {content, totalElements, number, size}
  // instead. Normalize here rather than trust every generation to remember
  // the plain-map instruction (see CrewOrchestrator._run_backend_generation's
  // supplemental prompt) — belt-and-suspenders, not the primary mechanism.
  const _normalize = (json: any): ApiResponse<T> => {
    if (json && Array.isArray(json.content)) {
      const size = json.size ?? limit
      const number = json.number ?? 0
      return {
        data: json.content, total: json.totalElements ?? json.content.length,
        limit: size, offset: number * size,
        hasMore: json.totalPages != null ? number + 1 < json.totalPages : false,
      }
    }
    return json as ApiResponse<T>
  }

  const fetchData = useCallback(async () => {
    abortRef.current?.abort()
    const controller = new AbortController()
    abortRef.current = controller
    setLoading(true)
    setError(null)
    try {
      const res = await _fetchWithRetry(buildUrl(offset), { signal: controller.signal })
      if (controller.signal.aborted) return
      if (!res.ok) throw new Error(`API error: ${res.status}`)
      const json = _normalize(await res.json())
      if (controller.signal.aborted) return
      setData(json.data)
      setTotal(json.total)
      setHasMore(json.hasMore)
      currentOffset.current = offset + json.data.length
    } catch (e: unknown) {
      if (e instanceof DOMException && e.name === 'AbortError') return
      setError(e instanceof Error ? e.message : 'Unknown error')
    } finally {
      if (!controller.signal.aborted) setLoading(false)
    }
  }, [buildUrl, offset])

  const fetchMore = useCallback(async () => {
    if (!hasMore || loading) return
    setLoading(true)
    try {
      const res = await _fetchWithRetry(buildUrl(currentOffset.current))
      if (!res.ok) throw new Error(`API error: ${res.status}`)
      const json = _normalize(await res.json())
      setData(prev => [...prev, ...json.data])
      setHasMore(json.hasMore)
      currentOffset.current += json.data.length
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Unknown error')
    } finally {
      setLoading(false)
    }
  }, [buildUrl, hasMore, loading])

  useEffect(() => {
    if (autoFetch) fetchData()
    return () => { abortRef.current?.abort() }
  }, [fetchData, autoFetch])

  return { data, total, loading, error, hasMore, refetch: fetchData, fetchMore }
}

// Shared row-fetcher for skill templates that just need a flat array of
// rows (KPI dashboards, charts, maps, grids, exports, calendars, feeds,
// etc.) without the full paginated envelope useApi() tracks. One place that
// knows about every response shape a backend might return — the plain
// {data: [...]} envelope, Java's raw Page<T> {content: [...]}, and a bare
// array — instead of every template reimplementing its own fetch +
// j.data-or-j.content fallback. That duplication is exactly how a
// Java-only "j.data is always undefined" bug went unnoticed in over a
// dozen templates at once; fixing it in one shared place means it can't
// happen again in a thirteenth.
// Java controllers are generated against Spring Data's own page/size
// convention, never this platform's limit/offset — reproduced directly:
// every caller here that only passed `limit` (ChartPanel, CardGrid, every
// skill template that just wants "up to N rows") silently got capped at a
// Java controller's own `size` default (usually 20) no matter how high
// `limit` was set, since the Java side never saw a `size`/`page` param at
// all. Derive and add both aliases here, once, so every caller of
// fetchTableRows/fetchTablePage is covered without each one having to
// know which backend language it's talking to.
function _withJavaPaginationAliases(params: Record<string, string | number>): Record<string, string | number> {
  const merged: Record<string, string | number> = { ...params }
  if (merged.limit != null && merged.size == null) merged.size = merged.limit
  if (merged.page == null) {
    const limitNum = Number(merged.limit ?? 0) || 1
    merged.page = merged.offset != null ? Math.floor(Number(merged.offset) / limitNum) : 0
  }
  return merged
}

export async function fetchTableRows(
  table: string,
  params: Record<string, string | number> = {}
): Promise<any[]> {
  const qs = new URLSearchParams(
    Object.entries(_withJavaPaginationAliases(params)).map(([k, v]) => [k, String(v)])
  ).toString()
  const res = await _fetchWithRetry(`${_API_BASE}/api/${table}${qs ? `?${qs}` : ''}`)
  if (!res.ok) throw new Error(`API error: ${res.status}`)
  const json = await res.json()
  if (Array.isArray(json)) return json
  return json?.data ?? json?.content ?? []
}

// Same shapes as fetchTableRows, plus the row count — for callers (query
// builders, paginated tables) that need to know how many rows exist beyond
// what was fetched, not just the rows themselves.
export async function fetchTablePage(
  table: string,
  params: Record<string, string | number> = {}
): Promise<{ data: any[]; total: number }> {
  const qs = new URLSearchParams(
    Object.entries(_withJavaPaginationAliases(params)).map(([k, v]) => [k, String(v)])
  ).toString()
  const res = await _fetchWithRetry(`${_API_BASE}/api/${table}${qs ? `?${qs}` : ''}`)
  if (!res.ok) throw new Error(`API error: ${res.status}`)
  const json = await res.json()
  const data = Array.isArray(json) ? json : json?.data ?? json?.content ?? []
  const total = json?.total ?? json?.totalElements ?? data.length
  return { data, total }
}

export async function apiAggregate(
  table: string,
  options: { groupBy?: string; metric?: string; column?: string; filter?: string; limit?: number } = {}
): Promise<AggregateResponse> {
  const params = new URLSearchParams()
  if (options.groupBy) params.set('groupBy', options.groupBy)
  if (options.metric) params.set('metric', options.metric)
  if (options.column) params.set('column', options.column)
  if (options.filter) params.set('filter', options.filter)
  if (options.limit) params.set('limit', String(options.limit))
  const res = await _fetchWithRetry(`${_API_BASE}/api/${table}/aggregate?${params.toString()}`)
  if (!res.ok) throw new Error(`Aggregate API error: ${res.status}`)
  return res.json()
}

export async function apiMetadata(): Promise<{ tables: Array<{ table: string; rowCount: number; columns: Array<{ name: string; type: string }> }> }> {
  const res = await _fetchWithRetry(`${_API_BASE}/api/metadata`)
  if (!res.ok) throw new Error(`Metadata API error: ${res.status}`)
  return res.json()
}

// --- Mutation helpers (Create / Update / Delete) ---

export async function apiPost<T = Record<string, unknown>>(
  table: string,
  body: Record<string, unknown>
): Promise<{ data: T; id: number }> {
  const res = await _fetchWithRetry(`${_API_BASE}/api/${table}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({ detail: `Error ${res.status}` }))
    throw new Error(err.detail || `Create failed: ${res.status}`)
  }
  return res.json()
}

export async function apiPut<T = Record<string, unknown>>(
  table: string,
  id: number,
  body: Record<string, unknown>
): Promise<{ data: T }> {
  const res = await _fetchWithRetry(`${_API_BASE}/api/${table}/${id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({ detail: `Error ${res.status}` }))
    throw new Error(err.detail || `Update failed: ${res.status}`)
  }
  return res.json()
}

export async function apiDelete(
  table: string,
  id: number
): Promise<{ deleted: boolean; id: number }> {
  const res = await _fetchWithRetry(`${_API_BASE}/api/${table}/${id}`, {
    method: 'DELETE',
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({ detail: `Error ${res.status}` }))
    throw new Error(err.detail || `Delete failed: ${res.status}`)
  }
  return res.json()
}
