"""
McpCrewOrchestrator — generates a FastMCP server exposing either:
  - a deterministic, read-only API over an existing SQLite database's selected
    tables ("datastore" source), or
  - tools that call an existing external HTTP API's selected endpoints directly
    ("api" source).

Design principle (see the plan): once a table's columns or an endpoint's
parameters are known (from mcp_introspect.py, plus whatever the user picked and
described in the UI), the resulting route/tool code has an entirely mechanical
shape — generated by plain code here, not an LLM completion. The one optional
LLM call in this pipeline exists only to improve a tool's name/description when
the user left it blank; every other file is deterministic templating, and
generation must succeed even if that LLM call fails.

v1 is deliberately read-only for the "api" source (matches "connect to get
data" — no POST/PUT/DELETE tools are generated), and the "datastore" source's
backing API is a read-only wrapper for the same reason — this is a data-access
layer for an MCP client to query, not a general-purpose CRUD product API.

The backing API (datastore source) and the MCP server are two genuinely
SEPARATE projects/processes/ports: generate_backing_api() produces a standalone
FastAPI project (registered and run via WebAPIGenerator's own registry/runner,
so it shows up in the Web API tab like any other API project), and
_generate_datastore_mcp_files() produces the MCP server's own files, whose tools
call that backing API over real HTTP. They're on different ports, so a tool's
outbound call is never a same-process loopback — no deadlock risk. (An earlier
version tried keeping both in one process with the MCP tools calling their own
query functions in-process instead of over HTTP, specifically to avoid that
same deadlock risk — this two-process version removes the risk at its root
instead, at the cost of an extra port/process pair per MCP project, which the
caller (server.py) is responsible for keeping in lifecycle sync — see
_run_mcp_generate/api_mcp_delete/api_mcp_start there.)
"""

import json
import re
from pathlib import Path
from typing import Callable, Optional


class McpCrewOrchestrator:
    def __init__(self, progress: Optional[Callable] = None):
        self.progress = progress
        self.files: dict[str, str] = {}
        self.project_dir: Optional[Path] = None

    def _p(self, msg: str):
        if self.progress:
            self.progress(msg)
        print(f"[mcp-crew] {msg}", flush=True)

    def _flush_to_disk(self):
        if not self.project_dir:
            return
        for fpath, content in self.files.items():
            out = self.project_dir / fpath
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(content, encoding="utf-8")

    def _call_llm(self, system_prompt: str, user_prompt: str, max_tokens: int = 4000) -> dict:
        from agents.llm import chat_json
        messages = [{"role": "user", "content": user_prompt}]
        return chat_json(messages, system=system_prompt, max_tokens=max_tokens)

    # ── Main entry point ──────────────────────────────────────────────────────

    def generate(self, project_dir: Path, project_name: str, source_type: str,
                 source_config: dict, mcp_options: dict, instructions: str = "") -> dict:
        """
        source_type is "datastore", "api", or "both" — "both" combines a
        datastore AND an external API into ONE MCP server, tools from each
        side calling their own base URL independently (see
        _generate_combined_mcp_files). The two source kinds are treated as
        independent, additive steps below (has_datastore/has_api) rather
        than mutually exclusive branches, so "both" just means both run.

        For a datastore source (alone or combined), source_config
        ["backingApiBaseUrl"] must already be set — the caller (server.py)
        is responsible for generating, registering, and starting the
        standalone backing API (via generate_backing_api + WebAPIGenerator's
        own registry/runner) BEFORE calling this, since that project lives
        outside this orchestrator's own project_dir and needs its own port
        from a different pool.

        source_config["customTools"], if present, are business-logic/join
        tools already designed (via design_custom_tools, called by the
        caller BEFORE generate_backing_api — those tools' /api/custom/<name>
        routes have to exist on the backing API before this function's own
        MCP-side wrappers can call them) — this function just appends them
        to the tool list and generates their MCP-side wrapper, it does not
        design or validate them itself.
        """
        self.project_dir = project_dir
        self._p("crew:Stage 1/4 — Authoring descriptions...")

        has_datastore = source_type in ("datastore", "both")
        has_api = source_type in ("api", "both")
        if not has_datastore and not has_api:
            raise ValueError(f"Unknown source_type: {source_type}")

        if has_datastore:
            self._fill_missing_table_descriptions(source_config["tables"], instructions)
        if has_api:
            self._fill_missing_endpoint_descriptions(source_config["endpoints"], instructions)

        self._p("crew:Stage 2/4 — Building tool list...")
        datastore_tools: list[dict] = []
        api_tools: list[dict] = []
        if has_datastore:
            datastore_tools = self._tools_for_datastore(source_config["tables"])
            for ct in source_config.get("customTools", []):
                datastore_tools.append({**ct, "path": f"/api/custom/{ct['name']}"})
        if has_api:
            api_tools = self._tools_for_api(source_config["endpoints"])
        tools = datastore_tools + api_tools

        self._fill_missing_descriptions(tools, source_type)
        self._p(f"skill:{len(tools)} tool(s) defined")

        self._p("crew:Stage 3/4 — Generating server code...")
        if has_datastore and not source_config.get("backingApiBaseUrl"):
            raise ValueError("backingApiBaseUrl is required for a datastore source")
        if has_datastore and has_api:
            self._generate_combined_mcp_files(
                project_name, datastore_tools, api_tools, source_config["backingApiBaseUrl"], source_config,
            )
        elif has_datastore:
            self._generate_datastore_mcp_files(project_name, tools, source_config["backingApiBaseUrl"])
        else:
            self._generate_api_server(project_name, source_config, tools)

        metadata = {
            "sourceType": source_type,
            "instructions": instructions,
            "datastore": (
                {"dbPath": source_config["dbPath"], "tables": source_config["tables"],
                 "backingApiProject": source_config.get("backingApiProject"),
                 "backingApiBaseUrl": source_config.get("backingApiBaseUrl")}
                if has_datastore else None
            ),
            "api": (
                {"baseUrl": source_config["baseUrl"], "authType": source_config.get("authType", "none"),
                 "endpoints": source_config["endpoints"]}
                if has_api else None
            ),
            "tools": tools,
        }
        self.files["metadata.json"] = json.dumps(metadata, indent=2, ensure_ascii=False)
        self.files["requirements.txt"] = (
            "fastmcp>=2.0\nhttpx>=0.27.0\npython-dotenv>=1.0.0\nfastapi>=0.110.0\nuvicorn>=0.29.0\n"
        )
        self.files["README.md"] = self._generate_readme(project_name, source_type, tools)

        self._p("crew:Stage 4/4 — Writing files...")
        self._flush_to_disk()
        self._p(f"skill:Generated {len(self.files)} file(s)")

        return {"metadata": metadata, "files": self.files, "tools": tools}

    # ── Tool list construction (deterministic) ──────────────────────────────

    def _tools_for_datastore(self, tables: list[dict]) -> list[dict]:
        tools = []
        for t in tables:
            table = t["name"]
            pk = next((c["name"] for c in t["columns"] if c.get("primaryKey")), t["columns"][0]["name"])
            singular = _singularize(table)
            tools.append({
                "name": f"list_{table}",
                "description": t.get("description", "").strip() or f"List rows from the {table} table.",
                "method": "GET", "path": f"/api/{table}", "kind": "list",
                "table": table, "pk": pk,
            })
            user_desc = t.get("description", "").strip()
            get_desc = (
                f"{user_desc.rstrip('.')} — looked up by {pk}."
                if user_desc else f"Get a single row from the {table} table by its {pk}."
            )
            tools.append({
                "name": f"get_{singular}",
                "description": get_desc,
                "method": "GET", "path": f"/api/{table}/{{id}}", "kind": "detail",
                "table": table, "pk": pk,
            })
        return tools

    def _tools_for_api(self, endpoints: list[dict]) -> list[dict]:
        tools = []
        for ep in endpoints:
            if ep.get("method", "GET").upper() != "GET":
                continue  # v1 is read-only — see module docstring
            tools.append({
                "name": _tool_name_from_endpoint(ep),
                "description": (ep.get("description") or ep.get("summary") or "").strip()
                               or f"GET {ep['path']}",
                "method": "GET", "path": ep["path"],
                "parameters": ep.get("parameters", []),
            })
        return tools

    def _fill_missing_table_descriptions(self, tables: list[dict], instructions: str = ""):
        """
        Best-effort LLM pass, run BEFORE tool-list construction so mechanical
        tool descriptions (which quote the table's own description) inherit
        something better than a blank string. Mutates `tables` in place, only
        filling in blanks — never overwrites a description the user already
        typed. Never blocks generation on failure, same as every other
        LLM-polish step in this file. `instructions`, if given, is passed as
        extra business context (e.g. what the data is actually used for) —
        purely to inform wording, it never changes WHICH tables/columns exist.
        """
        need_help = {}
        for t in tables:
            missing_cols = [c["name"] for c in t["columns"] if not (c.get("description") or "").strip()]
            if not (t.get("description") or "").strip() or missing_cols:
                need_help[t["name"]] = {
                    "columns": [{"name": c["name"], "type": c["type"]} for c in t["columns"]],
                    "needsTableDescription": not (t.get("description") or "").strip(),
                    "columnsNeedingDescription": missing_cols,
                }
        if not need_help:
            return
        try:
            context = f"\n\nBusiness context (for wording only): {instructions}" if instructions.strip() else ""
            result = self._call_llm(
                "You write short, clear one-sentence descriptions for database tables and "
                "their columns, given only names and types (no sample data). Return JSON: "
                '{"tables": {"table_name": {"description": "...", '
                '"columns": {"col_name": "..."}}}}. Only include the table description if '
                "needsTableDescription was true, and only include columns that were listed "
                "in columnsNeedingDescription. One sentence each, plain language, no markdown.",
                json.dumps(need_help, indent=2) + context,
                max_tokens=2000,
            )
            authored = result.get("tables", {})
            if not isinstance(authored, dict):
                return
            for t in tables:
                entry = authored.get(t["name"])
                if not isinstance(entry, dict):
                    continue
                if not (t.get("description") or "").strip() and isinstance(entry.get("description"), str):
                    t["description"] = entry["description"].strip()
                col_descs = entry.get("columns") if isinstance(entry.get("columns"), dict) else {}
                for c in t["columns"]:
                    if not (c.get("description") or "").strip() and isinstance(col_descs.get(c["name"]), str):
                        c["description"] = col_descs[c["name"]].strip()
        except Exception as e:
            self._p(f"skill:Table/column description authoring skipped ({e}) — descriptions may be blank")

    def _fill_missing_endpoint_descriptions(self, endpoints: list[dict], instructions: str = ""):
        """Same idea as _fill_missing_table_descriptions, for the API source's
        discovered endpoints — fills description only where blank."""
        need_help = [e for e in endpoints if not (e.get("description") or "").strip()]
        if not need_help:
            return
        try:
            context = f"\n\nBusiness context (for wording only): {instructions}" if instructions.strip() else ""
            result = self._call_llm(
                "You write short, clear one-sentence descriptions for HTTP API endpoints, "
                "given only their method, path, and any summary/parameters. Return JSON: "
                '{"descriptions": {"METHOD /path": "..."}}. One sentence each, plain '
                "language, no markdown.",
                json.dumps([
                    {"key": f"{e['method']} {e['path']}", "summary": e.get("summary"),
                     "parameters": e.get("parameters", [])}
                    for e in need_help
                ], indent=2) + context,
                max_tokens=2000,
            )
            descs = result.get("descriptions", {})
            if isinstance(descs, dict):
                for e in endpoints:
                    key = f"{e['method']} {e['path']}"
                    if not (e.get("description") or "").strip() and isinstance(descs.get(key), str):
                        e["description"] = descs[key].strip()
        except Exception as ex:
            self._p(f"skill:Endpoint description authoring skipped ({ex}) — descriptions may be blank")

    def _fill_missing_descriptions(self, tools: list[dict], source_type: str):
        """Best-effort LLM pass to write a nicer description for any tool that's
        still just the mechanical fallback — never blocks generation on failure."""
        need_help = [t for t in tools if t["description"].startswith(("List rows", "Get a single row", "GET /"))]
        if not need_help:
            return
        try:
            result = self._call_llm(
                "You write short, clear one-sentence descriptions for MCP tools, given their "
                "name and what they technically do. Return JSON: "
                '{"descriptions": {"tool_name": "new description", ...}}. '
                "One sentence each, plain language, no markdown.",
                "Tools needing better descriptions:\n" + json.dumps(
                    [{"name": t["name"], "current": t["description"]} for t in need_help], indent=2
                ),
                max_tokens=1500,
            )
            new_descs = result.get("descriptions", {})
            if isinstance(new_descs, dict):
                for t in tools:
                    if t["name"] in new_descs and isinstance(new_descs[t["name"]], str):
                        t["description"] = new_descs[t["name"]].strip()
        except Exception as e:
            self._p(f"skill:Tool description polish skipped ({e}) — using generated defaults")

    # ── Business-logic / join tools, designed from free-text instructions ───

    @staticmethod
    def _is_safe_select_sql(sql: str) -> bool:
        """
        Deterministic guard for LLM-designed custom-tool SQL — defense in
        depth on TOP of the read-only (mode=ro) SQLite connection every query
        already runs on (that connection alone already rejects any write at
        the driver level, verified directly earlier this session). This exists
        for a clean, immediate rejection instead of a cryptic SQLite error,
        and to block statement-stacking, which mode=ro doesn't specifically
        address (a stacked second statement could still just be another SELECT
        that isn't the one the tool's parameters were designed for).
        """
        if not sql or not sql.strip():
            return False
        stripped = sql.strip()
        upper = stripped.upper()
        if not (upper.startswith("SELECT") or upper.startswith("WITH")):
            return False
        # Reject a semicolon followed by more non-whitespace content — allows
        # a single optional trailing semicolon, blocks statement stacking.
        if re.search(r";\s*\S", stripped):
            return False
        blocked = ("INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "ATTACH", "DETACH",
                   "PRAGMA", "REPLACE", "CREATE", "TRUNCATE", "EXEC", "VACUUM")
        tokens = set(re.findall(r"[A-Za-z_]+", upper))
        return not (tokens & set(blocked))

    def design_custom_tools(self, all_tables: list[dict], instructions: str,
                             selected_table_names: set | None = None,
                             existing_names: set | None = None) -> dict:
        """
        One LLM call: given the FULL introspected schema (every table in the
        database, not just whichever ones the user picked for mechanical
        list/get tools) and free-text instructions, figures out TWO different
        things the instructions might be asking for:
          - additionalTables: tables not currently selected that should ALSO
            get direct list_/get_ tools (e.g. "also expose the vehicles
            table") — a genuinely different intent from a join, which needs
            the table's DATA but not necessarily its own raw tool.
          - customTools: 0-N tools backed by real SQL (joins, aggregates,
            filters), which can reference ANY table in the schema regardless
            of selection.
        Each custom-tool candidate is validated with _is_safe_select_sql and
        dropped (logged, not a hard failure) if it fails — mirrors how every
        other LLM output in this file is defensively normalized rather than
        trusted outright. Must be called BEFORE generate_backing_api, which
        is what actually wires the custom tools into real routes.
        """
        existing_names = existing_names or set()
        selected_table_names = selected_table_names or set()
        if not instructions.strip():
            return {"additionalTables": [], "customTools": []}
        schema_desc = [
            {"table": t["name"], "columns": [{"name": c["name"], "type": c["type"]} for c in t["columns"]],
             "foreignKeys": t.get("foreignKeys", []), "alreadySelected": t["name"] in selected_table_names}
            for t in all_tables
        ]
        try:
            result = self._call_llm(
                "You configure an MCP server's data tools, given a SQLite schema and a "
                "free-text request. Two DIFFERENT things the request might ask for: "
                "(1) exposing an entire table directly (e.g. 'also expose the vehicles "
                "table') — only for this, list its name in additionalTables, and ONLY if "
                "it's not already alreadySelected; (2) a specific business-logic query "
                "(joins, aggregates, filters) — for this, design a custom SQL tool instead, "
                "even if it needs a table that isn't selected (a join tool can use any "
                "table in the schema without that table needing its own list/get tool). "
                "Return JSON: {\"additionalTables\": [\"table_name\", ...], \"tools\": "
                "[{\"name\": \"snake_case_name\", \"description\": \"one sentence\", "
                "\"sql\": \"SELECT ... with ? placeholders for parameters, in order\", "
                "\"parameters\": [{\"name\": ..., \"type\": \"string\"|\"integer\"|\"number\"|"
                "\"boolean\", \"required\": bool, \"description\": ...}]}]}. Hard rules for "
                "\"sql\": MUST be a single read-only SELECT (or WITH ... SELECT) statement — "
                "never write, alter, or execute anything else; use table/column names "
                "EXACTLY as given in the schema; use `?` placeholders for every parameter, "
                "in the same order as the \"parameters\" array. Only act on what's clearly "
                "asked for or implied — don't invent unrelated tables or tools.",
                f"Schema:\n{json.dumps(schema_desc, indent=2)}\n\nInstructions:\n{instructions}\n\n"
                f"Names already in use (pick different names for new tools): {sorted(existing_names)}",
                max_tokens=3000,
            )
            candidates = result.get("tools", [])
            raw_additional = result.get("additionalTables", [])
        except Exception as e:
            self._p(f"skill:Instruction processing skipped ({e}) — instructions had no effect this time")
            return {"additionalTables": [], "customTools": []}

        all_table_names = {t["name"] for t in all_tables}
        additional_tables = [
            n for n in (raw_additional if isinstance(raw_additional, list) else [])
            if isinstance(n, str) and n in all_table_names and n not in selected_table_names
        ]
        if additional_tables:
            self._p(f"skill:Instructions asked for {len(additional_tables)} more table(s): {', '.join(additional_tables)}")

        custom_tools = []
        for c in (candidates if isinstance(candidates, list) else []):
            if not isinstance(c, dict):
                continue
            name = re.sub(r"[^a-z0-9_]", "_", str(c.get("name", "")).lower()).strip("_")
            sql = c.get("sql", "")
            if not name or name in existing_names:
                self._p(f"skill:Skipped a custom tool with a missing/duplicate name")
                continue
            if not self._is_safe_select_sql(sql):
                self._p(f"skill:Skipped custom tool '{name}' — its SQL didn't pass the read-only SELECT-only check")
                continue
            custom_tools.append({
                "name": name,
                "description": (c.get("description") or f"Custom query: {name}").strip(),
                "kind": "custom",
                "sql": sql.strip(),
                "parameters": c.get("parameters") if isinstance(c.get("parameters"), list) else [],
            })
            existing_names.add(name)
        if custom_tools:
            self._p(f"skill:Designed {len(custom_tools)} custom tool(s) from instructions")
        return {"additionalTables": additional_tables, "customTools": custom_tools}

    def select_additional_endpoints(self, all_endpoints: list[dict], selected_keys: set, instructions: str) -> list[str]:
        """
        API source's parallel to design_custom_tools' additionalTables — one
        LLM call, given every discovered GET endpoint and which are already
        selected, returns "METHOD path" keys for any more that the
        instructions ask for. No custom/composite tools here (out of scope
        for this pass — see mcp_orchestrator's module docstring); this only
        ever expands the mechanical tool set, so there's nothing to safety-
        guard the way custom SQL needs.
        """
        if not instructions.strip():
            return []
        catalog = [
            {"key": f"{e['method']} {e['path']}", "summary": e.get("summary"),
             "alreadySelected": f"{e['method']} {e['path']}" in selected_keys}
            for e in all_endpoints if e.get("method", "GET").upper() == "GET"
        ]
        try:
            result = self._call_llm(
                "Given a catalog of GET API endpoints and a free-text request, return the "
                "\"key\" of every endpoint the request asks to include that isn't already "
                "alreadySelected. Return JSON: {\"keys\": [\"METHOD /path\", ...]}. Only "
                "include what's clearly asked for or implied — don't invent unrelated ones.",
                f"Endpoints:\n{json.dumps(catalog, indent=2)}\n\nInstructions:\n{instructions}",
                max_tokens=1500,
            )
            keys = result.get("keys", [])
        except Exception as e:
            self._p(f"skill:Endpoint-selection instructions skipped ({e})")
            return []
        valid_keys = {c["key"] for c in catalog}
        additional = [k for k in keys if isinstance(k, str) and k in valid_keys and k not in selected_keys]
        if additional:
            self._p(f"skill:Instructions asked for {len(additional)} more endpoint(s)")
        return additional

    # ── Datastore source: backing API + MCP tools in one process ────────────

    def generate_backing_api(self, project_dir: Path, project_name: str, db_path: str, tables: list[dict],
                              custom_tools: list[dict] | None = None) -> dict:
        """
        A standalone, deterministic, read-only REST API over the given tables —
        its own project directory, meant to run as its own separate process/port
        (started via WebAPIGenerator's own api_runner, registered in its own
        registry, so it's independently visible/manageable in the Web API tab).
        No FastMCP/MCP code at all — the MCP server generated afterward calls
        this over real HTTP, on a genuinely different port, so there's no
        self-referential-loopback deadlock risk the way an in-process call would
        have. Writes files directly (doesn't use self.files/_flush_to_disk,
        since this project has its own directory, separate from self.project_dir).

        custom_tools (if any — see design_custom_tools) each become an extra
        `/api/custom/<name>` route running that tool's own validated
        read-only SQL, parameters bound positionally to its `?` placeholders.
        """
        custom_tools = custom_tools or []
        lines = [
            '"""',
            f"Generated read-only backing API for '{project_name}' — deterministic REST",
            "routes over an existing SQLite database. Generated by MCPGenerator; run as",
            "its own standalone project (see the Web API tab).",
            '"""',
            "import os",
            "import sqlite3",
            "",
            "from dotenv import load_dotenv",
            "from fastapi import FastAPI, HTTPException",
            "",
            "load_dotenv()",
            "",
            f'SOURCE_DB_PATH = os.environ.get("SOURCE_DB_PATH", r"{db_path}")',
            "# SQLite's URI parser needs forward slashes even on Windows.",
            '_DB_URI = "file:" + SOURCE_DB_PATH.replace("\\\\", "/") + "?mode=ro"',
            "",
            "",
            "def _get_conn():",
            "    # Read-only — this server must never be able to write to the source database.",
            "    return sqlite3.connect(_DB_URI, uri=True)",
            "",
        ]

        for t in tables:
            table = t["name"]
            pk = next((c["name"] for c in t["columns"] if c.get("primaryKey")), t["columns"][0]["name"])
            lines += [
                "",
                f"def _list_{table}(page: int = 0, limit: int = 20) -> dict:",
                "    conn = _get_conn()",
                "    try:",
                "        cur = conn.cursor()",
                f'        cur.execute(\'SELECT * FROM "{table}" LIMIT ? OFFSET ?\', (limit, page * limit))',
                "        cols = [d[0] for d in cur.description]",
                "        rows = [dict(zip(cols, r)) for r in cur.fetchall()]",
                f'        cur.execute(\'SELECT COUNT(*) FROM "{table}"\')',
                "        total = cur.fetchone()[0]",
                '        return {"items": rows, "total": total, "page": page, "limit": limit}',
                "    finally:",
                "        conn.close()",
                "",
                f"def _get_{table}(row_id: str) -> dict | None:",
                "    conn = _get_conn()",
                "    try:",
                "        cur = conn.cursor()",
                f'        cur.execute(\'SELECT * FROM "{table}" WHERE "{pk}" = ? LIMIT 1\', (row_id,))',
                "        row = cur.fetchone()",
                "        if row is None:",
                "            return None",
                "        cols = [d[0] for d in cur.description]",
                "        return dict(zip(cols, row))",
                "    finally:",
                "        conn.close()",
                "",
            ]

        for ct in custom_tools:
            params = ct.get("parameters", [])
            # A tool's SQL can legitimately need the SAME named parameter at
            # more than one `?` placeholder (e.g. WHERE (? IS NULL OR x = ?)
            # for an optional filter — observed directly from a real LLM
            # design) — dedupe by name for the function SIGNATURE (Python
            # rejects a duplicate argument name), but keep the FULL,
            # un-deduped list for the execute() binding tuple, repeating the
            # same local variable reference for each occurrence so every `?`
            # still gets the correct value.
            sig_parts = [f"{p['name']}: {_py_type(p.get('type'))} = None" for p in _dedupe_params(params)]
            arg_names = ", ".join(p["name"] for p in params)
            arg_tuple = f"({arg_names},)" if params else "()"
            lines += [
                "",
                f"def _custom_{ct['name']}({', '.join(sig_parts)}) -> dict:",
                "    conn = _get_conn()",
                "    try:",
                "        cur = conn.cursor()",
                f"        cur.execute({ct['sql']!r}, {arg_tuple})",
                "        cols = [d[0] for d in cur.description]",
                "        rows = [dict(zip(cols, r)) for r in cur.fetchall()]",
                '        return {"items": rows}',
                "    finally:",
                "        conn.close()",
                "",
            ]

        lines += [
            "",
            f'app = FastAPI(title="{project_name}")',
            "",
            "",
            '@app.get("/health")',
            "def health():",
            '    return {"status": "ok"}',
            "",
        ]

        for t in tables:
            table = t["name"]
            lines += [
                "",
                f'@app.get("/api/{table}")',
                f"def route_list_{table}(page: int = 0, limit: int = 20):",
                f"    return _list_{table}(page, limit)",
                "",
                f'@app.get("/api/{table}/{{row_id}}")',
                f"def route_get_{table}(row_id: str):",
                f"    result = _get_{table}(row_id)",
                "    if result is None:",
                '        raise HTTPException(404, "Not found")',
                "    return result",
                "",
            ]

        for ct in custom_tools:
            unique_params = _dedupe_params(ct.get("parameters", []))
            sig_parts = [f"{p['name']}: {_py_type(p.get('type'))} = None" for p in unique_params]
            # Calling _custom_<name>() positionally here must match ITS OWN
            # (also deduped) signature — one argument per unique name, not
            # the raw parameter list, which may repeat a name for a SQL
            # placeholder used twice (see _custom_<name>'s own comment).
            arg_names = ", ".join(p["name"] for p in unique_params)
            lines += [
                "",
                f'@app.get("/api/custom/{ct["name"]}")',
                f"def route_custom_{ct['name']}({', '.join(sig_parts)}):",
                f"    return _custom_{ct['name']}({arg_names})",
                "",
            ]

        db_path_posix = (db_path or "").replace("\\", "/")
        files = {
            "src/main.py": "\n".join(lines),
            "src/__init__.py": "",
            "requirements.txt": "fastapi>=0.110.0\nuvicorn>=0.29.0\npython-dotenv>=1.0.0\n",
            # Unquoted, forward-slash form — see _generate_datastore_mcp_files's
            # comment on why a quoted backslash path corrupts under python-dotenv.
            ".env.example": f"SOURCE_DB_PATH={db_path_posix}\n",
            ".env": f"SOURCE_DB_PATH={db_path_posix}\n",
        }
        for fpath, content in files.items():
            out = project_dir / fpath
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(content, encoding="utf-8")
        return {"files": files}

    def _generate_datastore_mcp_files(self, project_name: str, tools: list[dict], backing_api_base_url: str):
        """
        The MCP server's own files for a datastore source — no database access
        or FastAPI REST routes at all here; every tool calls the separately
        running backing API (see generate_backing_api) over real HTTP, on its
        own port, so there's no self-referential loopback risk.
        """
        base_url = backing_api_base_url.rstrip("/")
        lines = [
            '"""',
            f"Generated MCP server for '{project_name}' — tools that call this project's",
            f"own backing API at {base_url} (see the Web API tab) for the actual data.",
            '"""',
            "import os",
            "",
            "import httpx",
            "from dotenv import load_dotenv",
            "from fastapi import FastAPI",
            "from fastmcp import FastMCP",
            "",
            "load_dotenv()",
            "",
            f'BASE_URL = os.environ.get("BACKING_API_BASE_URL", "{base_url}")',
            "",
            'mcp = FastMCP("' + project_name + '")',
            "mcp_app = mcp.http_app()",
            "app = FastAPI(title=\"" + project_name + "\", lifespan=mcp_app.lifespan)",
            "",
            "",
            '@app.get("/health")',
            "def health():",
            '    return {"status": "ok"}',
            "",
        ]

        for tool in tools:
            desc = tool["description"].replace('"""', "'''")
            kind = tool.get("kind")
            if kind == "list":
                lines += [
                    "",
                    '@mcp.tool()',
                    f"def {tool['name']}(page: int = 0, limit: int = 20) -> dict:",
                    f'    """{desc}"""',
                    f'    resp = httpx.get(BASE_URL + "{tool["path"]}", params={{"page": page, "limit": limit}}, timeout=15.0)',
                    "    resp.raise_for_status()",
                    "    return resp.json()",
                    "",
                ]
            elif kind == "detail":
                lines += [
                    "",
                    '@mcp.tool()',
                    f"def {tool['name']}(id: str) -> dict:",
                    f'    """{desc}"""',
                    f'    url = BASE_URL + f"{tool["path"]}"',
                    "    resp = httpx.get(url, timeout=15.0)",
                    "    if resp.status_code == 404:",
                    '        return {"error": "Not found"}',
                    "    resp.raise_for_status()",
                    "    return resp.json()",
                    "",
                ]
            else:  # "custom" — a business-logic/join tool designed from instructions
                # Deduped: a tool's SQL may use the same named parameter at more
                # than one `?` placeholder (see generate_backing_api's matching
                # comment) — the HTTP query string only needs each unique name
                # once; the backing API's own route handles repeating the value
                # into the SQL binding tuple.
                params = _dedupe_params(tool.get("parameters", []))
                sig_parts = [f"{p['name']}: {_py_type(p.get('type'))} = None" for p in params]
                path = tool.get("path") or f"/api/custom/{tool['name']}"
                lines += [
                    "",
                    '@mcp.tool()',
                    f"def {tool['name']}({', '.join(sig_parts)}) -> dict:",
                    f'    """{desc}"""',
                ]
                if params:
                    q_items = ", ".join(f'"{p["name"]}": {p["name"]}' for p in params)
                    lines += [
                        f"    params = {{k: v for k, v in {{{q_items}}}.items() if v is not None}}",
                        f'    resp = httpx.get(BASE_URL + "{path}", params=params, timeout=15.0)',
                    ]
                else:
                    lines += [f'    resp = httpx.get(BASE_URL + "{path}", timeout=15.0)']
                lines += [
                    "    resp.raise_for_status()",
                    "    return resp.json()",
                    "",
                ]

        lines += ["", "app.mount(\"/\", mcp_app)", ""]
        self.files["src/main.py"] = "\n".join(lines)
        self.files["src/__init__.py"] = ""
        self.files[".env.example"] = f"BACKING_API_BASE_URL={base_url}\n"
        self.files[".env"] = f"BACKING_API_BASE_URL={base_url}\n"

    # ── API source: tools call an existing external API directly ────────────

    def _generate_api_server(self, project_name: str, source_config: dict, tools: list[dict]):
        base_url = source_config["baseUrl"].rstrip("/")
        auth_type = source_config.get("authType", "none")

        lines = [
            '"""',
            f"Generated MCP server for '{project_name}' — tools that call an existing",
            f"external API at {base_url} directly. Read-only (GET) for v1.",
            '"""',
            "import os",
            "",
            "import httpx",
            "from dotenv import load_dotenv",
            "from fastapi import FastAPI",
            "from fastmcp import FastMCP",
            "",
            "load_dotenv()",
            "",
            f'BASE_URL = os.environ.get("TARGET_API_BASE_URL", "{base_url}")',
        ]
        if auth_type == "basic":
            lines += [
                "AUTH = (",
                '    (os.environ.get("TARGET_API_USERNAME"), os.environ.get("TARGET_API_PASSWORD"))',
                '    if os.environ.get("TARGET_API_USERNAME") else None',
                ")",
            ]
        else:
            lines += ["AUTH = None"]
        lines += [
            "",
            'mcp = FastMCP("' + project_name + '")',
            "mcp_app = mcp.http_app()",
            "app = FastAPI(title=\"" + project_name + "\", lifespan=mcp_app.lifespan)",
            "",
            "",
            '@app.get("/health")',
            "def health():",
            '    return {"status": "ok"}',
            "",
        ]

        for tool in tools:
            path_params, query_params = _split_params(tool.get("parameters", []), tool["path"])
            sig_parts = [f"{p}: str" for p in path_params] + [
                f"{p['name']}: {_py_type(p.get('type'))} = None" for p in query_params
            ]
            desc = tool["description"].replace('"""', "'''")
            lines += [
                "",
                '@mcp.tool()',
                f"def {tool['name']}({', '.join(sig_parts)}) -> dict:",
                f'    """{desc}"""',
                f'    url = BASE_URL + f"{tool["path"]}"',
            ]
            if query_params:
                q_items = ", ".join(f'"{p["name"]}": {p["name"]}' for p in query_params)
                lines += [
                    f"    params = {{k: v for k, v in {{{q_items}}}.items() if v is not None}}",
                    "    resp = httpx.get(url, params=params, auth=AUTH, timeout=15.0)",
                ]
            else:
                lines += ["    resp = httpx.get(url, auth=AUTH, timeout=15.0)"]
            lines += [
                "    resp.raise_for_status()",
                "    return resp.json()",
                "",
            ]

        lines += ["", "app.mount(\"/\", mcp_app)", ""]
        self.files["src/main.py"] = "\n".join(lines)
        self.files["src/__init__.py"] = ""

        username = source_config.get("username", "")
        password = source_config.get("password", "")
        # Unquoted — see the datastore branch's comment above on why a quoted
        # value is unsafe (python-dotenv's backslash-escape processing).
        self.files[".env.example"] = (
            f"TARGET_API_BASE_URL={base_url}\nTARGET_API_USERNAME=\nTARGET_API_PASSWORD=\n"
        )
        self.files[".env"] = (
            f"TARGET_API_BASE_URL={base_url}\n"
            f"TARGET_API_USERNAME={username}\nTARGET_API_PASSWORD={password}\n"
        )

    # ── Combined source: datastore AND external API in ONE server ───────────

    def _generate_combined_mcp_files(self, project_name: str, datastore_tools: list[dict], api_tools: list[dict],
                                      backing_api_base_url: str, api_source_config: dict):
        """
        Both a datastore AND an external API as sources in one MCP server —
        each side's tools call their own base URL independently, exactly as
        _generate_datastore_mcp_files/_generate_api_server render them
        individually (this duplicates their per-tool rendering rather than
        sharing it, deliberately: those two single-source functions stay
        completely untouched and still used as-is for the common single-
        source case, so this new path can't regress them).
        """
        backing_url = backing_api_base_url.rstrip("/")
        api_base_url = api_source_config["baseUrl"].rstrip("/")
        auth_type = api_source_config.get("authType", "none")

        lines = [
            '"""',
            f"Generated MCP server for '{project_name}' — combines two sources: this",
            f"project's own backing API at {backing_url} (datastore tools) and an",
            f"external API at {api_base_url} (API tools).",
            '"""',
            "import os",
            "",
            "import httpx",
            "from dotenv import load_dotenv",
            "from fastapi import FastAPI",
            "from fastmcp import FastMCP",
            "",
            "load_dotenv()",
            "",
            f'BACKING_API_BASE_URL = os.environ.get("BACKING_API_BASE_URL", "{backing_url}")',
            f'TARGET_API_BASE_URL = os.environ.get("TARGET_API_BASE_URL", "{api_base_url}")',
        ]
        if auth_type == "basic":
            lines += [
                "TARGET_API_AUTH = (",
                '    (os.environ.get("TARGET_API_USERNAME"), os.environ.get("TARGET_API_PASSWORD"))',
                '    if os.environ.get("TARGET_API_USERNAME") else None',
                ")",
            ]
        else:
            lines += ["TARGET_API_AUTH = None"]
        lines += [
            "",
            'mcp = FastMCP("' + project_name + '")',
            "mcp_app = mcp.http_app()",
            "app = FastAPI(title=\"" + project_name + "\", lifespan=mcp_app.lifespan)",
            "",
            "",
            '@app.get("/health")',
            "def health():",
            '    return {"status": "ok"}',
            "",
        ]

        # Datastore-origin tools — identical rendering to
        # _generate_datastore_mcp_files, just against BACKING_API_BASE_URL.
        for tool in datastore_tools:
            desc = tool["description"].replace('"""', "'''")
            kind = tool.get("kind")
            if kind == "list":
                lines += [
                    "", '@mcp.tool()',
                    f"def {tool['name']}(page: int = 0, limit: int = 20) -> dict:",
                    f'    """{desc}"""',
                    f'    resp = httpx.get(BACKING_API_BASE_URL + "{tool["path"]}", params={{"page": page, "limit": limit}}, timeout=15.0)',
                    "    resp.raise_for_status()",
                    "    return resp.json()",
                    "",
                ]
            elif kind == "detail":
                lines += [
                    "", '@mcp.tool()',
                    f"def {tool['name']}(id: str) -> dict:",
                    f'    """{desc}"""',
                    f'    url = BACKING_API_BASE_URL + f"{tool["path"]}"',
                    "    resp = httpx.get(url, timeout=15.0)",
                    "    if resp.status_code == 404:",
                    '        return {"error": "Not found"}',
                    "    resp.raise_for_status()",
                    "    return resp.json()",
                    "",
                ]
            else:  # "custom" — a business-logic/join tool designed from instructions
                params = _dedupe_params(tool.get("parameters", []))
                sig_parts = [f"{p['name']}: {_py_type(p.get('type'))} = None" for p in params]
                path = tool.get("path") or f"/api/custom/{tool['name']}"
                lines += ["", '@mcp.tool()', f"def {tool['name']}({', '.join(sig_parts)}) -> dict:", f'    """{desc}"""']
                if params:
                    q_items = ", ".join(f'"{p["name"]}": {p["name"]}' for p in params)
                    lines += [
                        f"    params = {{k: v for k, v in {{{q_items}}}.items() if v is not None}}",
                        f'    resp = httpx.get(BACKING_API_BASE_URL + "{path}", params=params, timeout=15.0)',
                    ]
                else:
                    lines += [f'    resp = httpx.get(BACKING_API_BASE_URL + "{path}", timeout=15.0)']
                lines += ["    resp.raise_for_status()", "    return resp.json()", ""]

        # API-origin tools — identical rendering to _generate_api_server,
        # just against TARGET_API_BASE_URL/TARGET_API_AUTH.
        for tool in api_tools:
            path_params, query_params = _split_params(tool.get("parameters", []), tool["path"])
            sig_parts = [f"{p}: str" for p in path_params] + [
                f"{p['name']}: {_py_type(p.get('type'))} = None" for p in query_params
            ]
            desc = tool["description"].replace('"""', "'''")
            lines += [
                "", '@mcp.tool()',
                f"def {tool['name']}({', '.join(sig_parts)}) -> dict:",
                f'    """{desc}"""',
                f'    url = TARGET_API_BASE_URL + f"{tool["path"]}"',
            ]
            if query_params:
                q_items = ", ".join(f'"{p["name"]}": {p["name"]}' for p in query_params)
                lines += [
                    f"    params = {{k: v for k, v in {{{q_items}}}.items() if v is not None}}",
                    "    resp = httpx.get(url, params=params, auth=TARGET_API_AUTH, timeout=15.0)",
                ]
            else:
                lines += ["    resp = httpx.get(url, auth=TARGET_API_AUTH, timeout=15.0)"]
            lines += ["    resp.raise_for_status()", "    return resp.json()", ""]

        lines += ["", "app.mount(\"/\", mcp_app)", ""]
        self.files["src/main.py"] = "\n".join(lines)
        self.files["src/__init__.py"] = ""

        username = api_source_config.get("username", "")
        password = api_source_config.get("password", "")
        self.files[".env.example"] = (
            f"BACKING_API_BASE_URL={backing_url}\nTARGET_API_BASE_URL={api_base_url}\n"
            f"TARGET_API_USERNAME=\nTARGET_API_PASSWORD=\n"
        )
        self.files[".env"] = (
            f"BACKING_API_BASE_URL={backing_url}\nTARGET_API_BASE_URL={api_base_url}\n"
            f"TARGET_API_USERNAME={username}\nTARGET_API_PASSWORD={password}\n"
        )

    def _generate_readme(self, project_name: str, source_type: str, tools: list[dict]) -> str:
        tool_lines = "\n".join(f"- `{t['name']}` — {t['description']}" for t in tools)
        return (
            f"# {project_name}\n\n"
            f"Generated MCP server ({source_type} source), served over Streamable HTTP at "
            f"`/mcp` (also see plain REST routes under `/api/*` if this is a datastore-backed "
            f"server, and interactive docs at `/docs`).\n\n"
            f"## Tools\n\n{tool_lines}\n"
        )


# ── Naming helpers ────────────────────────────────────────────────────────────

def _singularize(name: str) -> str:
    if name.endswith("ies"):
        return name[:-3] + "y"
    if name.endswith("s") and not name.endswith("ss"):
        return name[:-1]
    return name


def _tool_name_from_endpoint(ep: dict) -> str:
    segs = [s for s in ep["path"].split("/") if s]
    if segs and segs[-1].startswith("{"):
        resource = _singularize(segs[-2]) if len(segs) >= 2 else "item"
        name = f"get_{resource}_by_{segs[-1].strip('{}')}"
    else:
        resource = segs[-1] if segs else "root"
        name = f"list_{resource}"
    return re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_") or "tool"


def _split_params(parameters: list[dict], path: str) -> tuple[list[str], list[dict]]:
    path_param_names = re.findall(r"\{(\w+)\}", path)
    query_params = [p for p in parameters if p.get("in") == "query" and p.get("name")]
    return path_param_names, query_params


def _py_type(openapi_type: str | None) -> str:
    return {"integer": "int", "number": "float", "boolean": "bool"}.get(openapi_type, "str")


def _dedupe_params(params: list[dict]) -> list[dict]:
    """First-occurrence-wins dedup by name — a custom tool's SQL may
    legitimately reference the same named parameter at more than one `?`
    placeholder, which is fine in the SQL/binding tuple but would be a
    duplicate-argument SyntaxError in a generated Python function signature."""
    seen = set()
    out = []
    for p in params:
        if p["name"] not in seen:
            out.append(p)
            seen.add(p["name"])
    return out
