# requirements.txt:
# fastapi
# uvicorn
# python-dotenv
# openai
# httpx
# openpyxl
# PyMuPDF

"""
Unified App Server — auto-generated by TurboUIGen.
Provides:
  - SQLite database from schema.sql + seed.sql
  - Auto-REST endpoints for every table (GET list, GET by id, GET aggregate)
  - /api/metadata — API catalog for discoverability
  - /api/chat — LLM-powered data chat using API metadata awareness
  - Static file serving (production mode)
"""

import json
import math
import os
import re
import sqlite3
import ssl
import tempfile
from pathlib import Path
from typing import Any

import httpx
import uvicorn
from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, Query, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

load_dotenv(Path(".") / ".env")

# --- Configuration ---
DB_PATH = os.getenv("DB_PATH", "data.db")
LITELLM_API_BASE = os.getenv("LITELLM_API_BASE", "")
LITELLM_API_KEY = os.getenv("LITELLM_API_KEY", "")
LITELLM_SSL_CERT = os.getenv("LITELLM_SSL_CERT", "")
LITELLM_TIMEOUT = int(os.getenv("LITELLM_TIMEOUT", "180"))
LITELLM_MODEL = os.getenv("LITELLM_MODEL", "claude-sonnet-4-6")
API_PORT = int(os.getenv("API_PORT", "8080"))


# --- SSL + LLM Client setup ---
def _make_ssl_context() -> ssl.SSLContext | bool:
    if not LITELLM_SSL_CERT:
        return True
    ctx = ssl.create_default_context()
    cert_content = LITELLM_SSL_CERT.replace("\\n", "\n")
    ctx.load_verify_locations(cadata=cert_content)
    return ctx


def _make_http_client():
    return httpx.AsyncClient(
        verify=_make_ssl_context(),
        timeout=httpx.Timeout(connect=30.0, read=float(LITELLM_TIMEOUT), write=60.0, pool=30.0),
        limits=httpx.Limits(max_connections=20, max_keepalive_connections=5, keepalive_expiry=30),
    )

http_client = _make_http_client()

llm_client = None
if LITELLM_API_BASE:
    from openai import AsyncOpenAI
    base_url = LITELLM_API_BASE.rstrip("/") + "/v1"
    llm_client = AsyncOpenAI(
        api_key=LITELLM_API_KEY,
        base_url=base_url,
        http_client=http_client,
        timeout=LITELLM_TIMEOUT,
    )


# --- Database ---
def _get_db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def _init_db():
    """Initialize database from schema.sql and seed.sql if they exist."""
    conn = _get_db()
    schema_file = Path("schema.sql")
    seed_file = Path("seed.sql")

    if schema_file.exists():
        conn.executescript(schema_file.read_text(encoding="utf-8"))
        print(f"[db] Executed schema.sql")

    if seed_file.exists():
        # Only seed if database is empty (avoid UNIQUE constraint errors on restart)
        tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").fetchall()
        is_empty = True
        for (table_name,) in tables:
            count = conn.execute(f"SELECT COUNT(*) FROM [{table_name}]").fetchone()[0]
            if count > 0:
                is_empty = False
                break
        if is_empty:
            conn.executescript(seed_file.read_text(encoding="utf-8"))
            print(f"[db] Executed seed.sql")
        else:
            print(f"[db] Skipped seed.sql (database already has data)")

    conn.close()


def _get_tables() -> list[str]:
    conn = _get_db()
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
    ).fetchall()
    conn.close()
    return [r["name"] for r in rows]


def _get_table_schema(table: str) -> list[dict]:
    conn = _get_db()
    rows = conn.execute(f"PRAGMA table_info('{table}')").fetchall()
    conn.close()
    return [{"name": r["name"], "type": r["type"], "pk": bool(r["pk"]), "nullable": not r["notnull"]} for r in rows]


def _get_table_count(table: str) -> int:
    conn = _get_db()
    count = conn.execute(f"SELECT COUNT(*) as c FROM [{table}]").fetchone()["c"]
    conn.close()
    return count


# --- App ---
app = FastAPI(title="TurboUI App Server")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_origin_regex=r"http://(localhost|127\.0\.0\.1)(:\d+)?",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --- API Metadata ---
_api_metadata: list[dict] = []


def _build_metadata():
    """Build API metadata from discovered tables."""
    global _api_metadata
    _api_metadata = []
    tables = _get_tables()
    for table in tables:
        schema = _get_table_schema(table)
        count = _get_table_count(table)
        columns = [col["name"] for col in schema]
        numeric_cols = [col["name"] for col in schema if col["type"].upper() in ("INTEGER", "REAL", "NUMERIC", "FLOAT", "DOUBLE")]

        _api_metadata.append({
            "table": table,
            "description": f"Data table '{table}' with {count} rows",
            "rowCount": count,
            "columns": schema,
            "endpoints": {
                "list": f"/api/data/{table}",
                "byId": f"/api/data/{table}/{{id}}",
                "aggregate": f"/api/data/{table}/aggregate",
            },
            "queryParams": {
                "list": {
                    "limit": "number (default 100, max 1000)",
                    "offset": "number (default 0)",
                    "sort": f"column name ({', '.join(columns[:5])}...)",
                    "order": "asc|desc (default asc)",
                    "filter": "column:operator:value (operators: eq,ne,gt,lt,gte,lte,like,in)",
                },
                "aggregate": {
                    "groupBy": f"column name ({', '.join(columns[:5])}...)",
                    "metric": f"sum|avg|min|max|count",
                    "column": f"numeric column ({', '.join(numeric_cols[:3])}...)",
                    "filter": "same as list",
                },
            },
        })


@app.get("/api/metadata")
async def get_metadata():
    return {"tables": _api_metadata, "chatEndpoint": "/api/chat"}


# --- Generic Data Endpoints ---
def _parse_filter(filter_str: str) -> tuple[str, list]:
    """Parse 'column:operator:value' into SQL WHERE clause."""
    parts = filter_str.split(":", 2)
    if len(parts) != 3:
        return "", []
    col, op, val = parts
    col_safe = re.sub(r"[^a-zA-Z0-9_]", "", col)
    ops = {"eq": "=", "ne": "!=", "gt": ">", "lt": "<", "gte": ">=", "lte": "<=", "like": "LIKE"}
    if op == "in":
        values = val.split(",")
        placeholders = ",".join("?" * len(values))
        return f"[{col_safe}] IN ({placeholders})", values
    if op not in ops:
        return "", []
    sql_op = ops[op]
    if op == "like":
        val = f"%{val}%"
    return f"[{col_safe}] {sql_op} ?", [val]


@app.get("/api/data/{table}")
async def get_table_data(
    table: str,
    limit: int = Query(100, ge=1, le=1000),
    offset: int = Query(0, ge=0),
    sort: str | None = None,
    order: str = Query("asc", regex="^(asc|desc)$"),
    filter: str | None = None,
):
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    conn = _get_db()
    where_clause = ""
    params: list = []

    if filter:
        filters = filter.split(";")
        conditions = []
        for f in filters:
            clause, vals = _parse_filter(f)
            if clause:
                conditions.append(clause)
                params.extend(vals)
        if conditions:
            where_clause = "WHERE " + " AND ".join(conditions)

    count_sql = f"SELECT COUNT(*) as c FROM [{table}] {where_clause}"
    total = conn.execute(count_sql, params).fetchone()["c"]

    sort_clause = ""
    if sort:
        sort_safe = re.sub(r"[^a-zA-Z0-9_]", "", sort)
        sort_clause = f"ORDER BY [{sort_safe}] {order.upper()}"

    query = f"SELECT * FROM [{table}] {where_clause} {sort_clause} LIMIT ? OFFSET ?"
    rows = conn.execute(query, params + [limit, offset]).fetchall()
    conn.close()

    data = [dict(r) for r in rows]
    return {
        "data": data,
        "total": total,
        "limit": limit,
        "offset": offset,
        "hasMore": (offset + limit) < total,
    }


@app.get("/api/data/{table}/{row_id}")
async def get_table_row(table: str, row_id: int):
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    conn = _get_db()
    row = conn.execute(f"SELECT * FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
    conn.close()

    if not row:
        raise HTTPException(status_code=404, detail="Row not found")
    return dict(row)


@app.get("/api/data/{table}/aggregate")
async def get_table_aggregate(
    table: str,
    groupBy: str | None = None,
    metric: str = Query("count", regex="^(sum|avg|min|max|count)$"),
    column: str | None = None,
    filter: str | None = None,
    limit: int = Query(50, ge=1, le=200),
):
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    where_clause = ""
    params: list = []
    if filter:
        filters = filter.split(";")
        conditions = []
        for f in filters:
            clause, vals = _parse_filter(f)
            if clause:
                conditions.append(clause)
                params.extend(vals)
        if conditions:
            where_clause = "WHERE " + " AND ".join(conditions)

    if metric == "count":
        agg_expr = "COUNT(*)"
    else:
        if not column:
            raise HTTPException(status_code=400, detail=f"'column' required for metric '{metric}'")
        col_safe = re.sub(r"[^a-zA-Z0-9_]", "", column)
        agg_expr = f"{metric.upper()}([{col_safe}])"

    conn = _get_db()
    if groupBy:
        group_safe = re.sub(r"[^a-zA-Z0-9_]", "", groupBy)
        query = f"SELECT [{group_safe}] as _group, {agg_expr} as _value FROM [{table}] {where_clause} GROUP BY [{group_safe}] ORDER BY _value DESC LIMIT ?"
        rows = conn.execute(query, params + [limit]).fetchall()
        conn.close()
        return {"data": [{"group": r["_group"], "value": r["_value"]} for r in rows]}
    else:
        query = f"SELECT {agg_expr} as _value FROM [{table}] {where_clause}"
        row = conn.execute(query, params).fetchone()
        conn.close()
        return {"value": row["_value"]}


# --- Chat Endpoint ---
class ChatMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    responseFormat: str = "auto"
    context: dict | None = None


def _build_chat_system_prompt() -> str:
    """Build a system prompt with API metadata awareness."""
    tables_info = []
    for meta in _api_metadata:
        cols = ", ".join(f"{c['name']} ({c['type']})" for c in meta["columns"])
        tables_info.append(
            f"- **{meta['table']}** ({meta['rowCount']} rows): {cols}\n"
            f"  Endpoints: GET {meta['endpoints']['list']}?limit=N&offset=N&sort=COL&order=asc|desc&filter=COL:OP:VAL\n"
            f"             GET {meta['endpoints']['aggregate']}?groupBy=COL&metric=sum|avg|min|max|count&column=COL"
        )
    tables_section = "\n".join(tables_info)

    return (
        "You are an expert data analyst for this application.\n\n"
        "## Available Data (via REST API)\n"
        f"{tables_section}\n\n"
        "## Filter syntax\n"
        "filter=column:operator:value  (operators: eq, ne, gt, lt, gte, lte, like, in)\n"
        "Multiple filters: filter=col1:eq:val1;col2:gt:val2\n\n"
        "## Response format rules\n"
        "- If the answer is best shown as a chart, wrap it in ```chart\\n{json}\\n``` "
        "where json is: {\"type\": \"bar\"|\"line\"|\"donut\"|\"scatter\", \"title\": \"...\", \"data\": [...], \"xKey\": \"fieldName\", \"yKeys\": [\"fieldName1\"]}\n"
        "- If the answer is best shown as a geographic map, wrap it in ```map\\n{json}\\n``` "
        "where json is: {\"mapType\": \"world\"|\"usa\", \"title\": \"...\", \"data\": [{\"id\": \"ISO2_CODE\", \"value\": number, \"label\": \"...\"}], "
        "\"valueLabel\": \"field description\", \"colorScheme\": \"blue\"|\"green\"|\"red\"|\"purple\"}\n"
        "  - Use mapType \"world\" for country-level data (id = ISO 3166-1 alpha-2 code like \"US\", \"DE\", \"CN\")\n"
        "  - Use mapType \"usa\" only if data has US state-level granularity (id = state FIPS or postal code)\n"
        "  - Use a map when the user asks to \"show on a map\", \"visualize geographically\", or when the data has a clear geographic dimension and the user asks for a spatial view\n"
        "- If best as a table, wrap it in ```table\\n[{...}, ...]\\n```\n"
        "- Otherwise respond in plain text with markdown formatting.\n"
        "- Use the actual data from the database to compute your answers.\n"
        "- When asked to show data, query it and include real values — never make up numbers.\n"
        "- For aggregations, use the aggregate endpoint mentally to describe the correct values.\n"
    )


def _parse_llm_response(text: str) -> dict[str, Any]:
    """Parse LLM response for embedded chart/table/map blocks."""
    map_match = re.search(r"```map\s*\n([\s\S]*?)\n```", text)
    if map_match:
        try:
            data = json.loads(map_match.group(1))
            clean = text[:map_match.start()].strip() + "\n\n" + text[map_match.end():].strip()
            return {"response": clean.strip(), "type": "map", "data": data}
        except json.JSONDecodeError:
            pass

    chart_match = re.search(r"```chart\s*\n([\s\S]*?)\n```", text)
    if chart_match:
        try:
            data = json.loads(chart_match.group(1))
            clean = text[:chart_match.start()].strip() + "\n\n" + text[chart_match.end():].strip()
            return {"response": clean.strip(), "type": "chart", "data": data}
        except json.JSONDecodeError:
            pass

    table_match = re.search(r"```table\s*\n([\s\S]*?)\n```", text)
    if table_match:
        try:
            data = json.loads(table_match.group(1))
            clean = text[:table_match.start()].strip() + "\n\n" + text[table_match.end():].strip()
            return {"response": clean.strip(), "type": "table", "data": data}
        except json.JSONDecodeError:
            pass

    try:
        data = json.loads(text)
        if isinstance(data, dict) and "type" in data:
            return {"response": text, "type": "chart", "data": data}
        if isinstance(data, list):
            return {"response": text, "type": "table", "data": data}
    except json.JSONDecodeError:
        pass

    return {"response": text, "type": "text", "data": None}


@app.post("/api/chat")
async def chat(request: ChatRequest):
    import asyncio
    from openai import AsyncOpenAI
    global llm_client, http_client

    if not llm_client:
        raise HTTPException(status_code=503, detail="LLM not configured — check .env credentials")

    try:
        system_prompt = _build_chat_system_prompt()
        if request.context:
            system_prompt += f"\n\nAdditional context: {json.dumps(request.context)}"

        if request.responseFormat == "chart":
            system_prompt += "\n\nIMPORTANT: Respond with a chart visualization using the ```chart format."
        elif request.responseFormat == "table":
            system_prompt += "\n\nIMPORTANT: Respond with tabular data using the ```table format."

        # Inject sample data into system prompt for accurate answers
        sample_data = {}
        conn = _get_db()
        for meta in _api_metadata[:5]:
            rows = conn.execute(f"SELECT * FROM [{meta['table']}] LIMIT 10").fetchall()
            sample_data[meta["table"]] = [dict(r) for r in rows]
        conn.close()
        system_prompt += f"\n\n## Sample data (first 10 rows per table)\n```json\n{json.dumps(sample_data, default=str, indent=2)}\n```"

        messages = [{"role": "system", "content": system_prompt}]
        # Keep only last 20 messages to avoid exceeding token limits
        recent = request.messages[-20:] if len(request.messages) > 20 else request.messages
        messages.extend([{"role": m.role, "content": m.content} for m in recent])

        last_err = None
        for _attempt in range(3):
            try:
                completion = await llm_client.chat.completions.create(
                    model=LITELLM_MODEL,
                    messages=messages,
                    temperature=0.3,
                )
                text = completion.choices[0].message.content
                return _parse_llm_response(text)
            except Exception as attempt_err:
                last_err = attempt_err
                print(f"[chat] attempt {_attempt+1} failed: {type(attempt_err).__name__}: {attempt_err}", flush=True)
                if _attempt < 2:
                    # Recreate HTTP client on connection errors (stale pool, SSL tear-down)
                    try:
                        await http_client.aclose()
                    except Exception:
                        pass
                    http_client = _make_http_client()
                    llm_client = AsyncOpenAI(
                        api_key=LITELLM_API_KEY,
                        base_url=LITELLM_API_BASE.rstrip("/") + "/v1",
                        http_client=http_client,
                        timeout=LITELLM_TIMEOUT,
                    )
                    await asyncio.sleep(2 * (_attempt + 1))
        raise HTTPException(status_code=500, detail=f"LLM call failed after 3 attempts: {last_err}")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# --- File upload endpoints (for Excel/PDF chat) ---
@app.post("/api/ingest/excel")
async def ingest_excel(file: UploadFile = File(...)):
    try:
        import openpyxl
        suffix = Path(file.filename or "upload.xlsx").suffix
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            content = await file.read()
            tmp.write(content)
            tmp_path = tmp.name

        wb = openpyxl.load_workbook(tmp_path, read_only=True, data_only=True)
        sheets = []
        for sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            rows_raw = list(ws.iter_rows(values_only=True))
            if not rows_raw:
                continue
            headers = [str(h) if h else f"col_{i}" for i, h in enumerate(rows_raw[0])]
            data_rows = [dict(zip(headers, row)) for row in rows_raw[1:]]
            schema = [{"name": h, "type": _detect_col_type([r.get(h) for r in data_rows[:50]])} for h in headers]
            sheets.append({
                "name": sheet_name,
                "schema": schema,
                "rows": data_rows[:100],
                "totalRows": len(data_rows),
                "sampleRows": data_rows[:10],
            })
        wb.close()
        os.unlink(tmp_path)
        return {"sheets": sheets}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/ingest/pdf")
async def ingest_pdf(file: UploadFile = File(...)):
    try:
        import fitz
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
            content = await file.read()
            tmp.write(content)
            tmp_path = tmp.name

        doc = fitz.open(tmp_path)
        chunks = [page.get_text() for page in doc]
        full_text = "\n".join(chunks)
        title = doc.metadata.get("title", "") if doc.metadata else ""
        page_count = len(doc)
        doc.close()
        os.unlink(tmp_path)
        return {"pages": page_count, "text": full_text, "chunks": chunks, "metadata": {"title": title, "pages": page_count}}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def _detect_col_type(values: list) -> str:
    non_empty = [v for v in values if v is not None and str(v).strip() != ""]
    if not non_empty:
        return "TEXT"
    numeric_count = sum(1 for v in non_empty if _is_numeric(v))
    if numeric_count == len(non_empty):
        return "REAL" if any("." in str(v) for v in non_empty) else "INTEGER"
    return "TEXT"


def _is_numeric(v) -> bool:
    try:
        float(v)
        return True
    except (ValueError, TypeError):
        return False


# --- Health ---
@app.get("/health")
async def health():
    tables = _get_tables()
    return {"status": "ok", "tables": len(tables), "database": DB_PATH}


# --- Startup ---
@app.on_event("startup")
async def startup():
    _init_db()
    _build_metadata()
    tables = _get_tables()
    print(f"\n  TurboUI App Server running on port {API_PORT}")
    print(f"  Database: {DB_PATH} ({len(tables)} tables)")
    print(f"  Endpoints:")
    for meta in _api_metadata:
        print(f"    GET /api/data/{meta['table']}  ({meta['rowCount']} rows)")
    print(f"    GET  /api/metadata        — API catalog")
    print(f"    POST /api/chat            — AI data chat")
    print(f"    GET  /health              — Health check\n")


# --- Static file serving (production) ---
dist_dir = Path("dist")
if dist_dir.exists():
    app.mount("/assets", StaticFiles(directory=str(dist_dir / "assets")), name="assets")

    @app.get("/{full_path:path}")
    async def serve_spa(full_path: str):
        file_path = dist_dir / full_path
        if file_path.exists() and file_path.is_file():
            return FileResponse(str(file_path))
        return FileResponse(str(dist_dir / "index.html"))


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=API_PORT)
