# requirements.txt:
# fastapi
# uvicorn
# python-dotenv
# openai
# httpx
# openpyxl
# PyMuPDF

"""
Unified App Server — auto-generated by TurboUIGen.
Provides:
  - SQLite database from schema.sql + seed.sql
  - Auto-REST endpoints for every table (GET list, GET by id, GET aggregate)
  - /api/metadata — API catalog for discoverability
  - /api/chat — LLM-powered data chat using API metadata awareness
  - Static file serving (production mode)
"""

import json
import math
import os
import re
import sqlite3
import ssl
import tempfile
from pathlib import Path
from typing import Any

import httpx
import uvicorn
from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, Query, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

load_dotenv(Path(".") / ".env")

# --- Configuration ---
DB_PATH = os.getenv("DB_PATH", "data.db")
LITELLM_API_BASE = os.getenv("LITELLM_API_BASE", "")
LITELLM_API_KEY = os.getenv("LITELLM_API_KEY", "")
LITELLM_SSL_CERT = os.getenv("LITELLM_SSL_CERT", "")
LITELLM_TIMEOUT = int(os.getenv("LITELLM_TIMEOUT", "180"))
LITELLM_MODEL = os.getenv("LITELLM_MODEL", "claude-sonnet-4-6")
API_PORT = int(os.getenv("API_PORT", "8080"))


# --- SSL + LLM Client setup ---
def _make_ssl_context() -> ssl.SSLContext | bool:
    if not LITELLM_SSL_CERT:
        return True
    ctx = ssl.create_default_context()
    cert_content = LITELLM_SSL_CERT.replace("\\n", "\n")
    ctx.load_verify_locations(cadata=cert_content)
    return ctx


def _make_http_client():
    return httpx.AsyncClient(
        verify=_make_ssl_context(),
        timeout=httpx.Timeout(connect=30.0, read=float(LITELLM_TIMEOUT), write=60.0, pool=30.0),
        limits=httpx.Limits(max_connections=20, max_keepalive_connections=5, keepalive_expiry=30),
    )

http_client = _make_http_client()

llm_client = None
if LITELLM_API_BASE:
    from openai import AsyncOpenAI
    base_url = LITELLM_API_BASE.rstrip("/") + "/v1"
    llm_client = AsyncOpenAI(
        api_key=LITELLM_API_KEY,
        base_url=base_url,
        http_client=http_client,
        timeout=LITELLM_TIMEOUT,
    )


# --- Database ---
def _get_db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def _init_db():
    """Initialize database from schema.sql and seed.sql if they exist.

    Supports incremental refinement: if database already has tables, only
    CREATE IF NOT EXISTS and seed NEW tables (those that are empty).
    """
    conn = _get_db()
    schema_file = Path("schema.sql")
    seed_file = Path("seed.sql")

    if schema_file.exists():
        existing_tables = {r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
        ).fetchall()}

        if not existing_tables:
            conn.executescript(schema_file.read_text(encoding="utf-8"))
            print(f"[db] Executed schema.sql (new database)")
        else:
            # Incremental: run schema with IF NOT EXISTS to add new tables
            schema_sql = schema_file.read_text(encoding="utf-8")
            # Inject IF NOT EXISTS into CREATE TABLE statements that lack it
            import re as _re
            schema_sql = _re.sub(
                r"CREATE\s+TABLE\s+(?!IF\s+NOT\s+EXISTS)",
                "CREATE TABLE IF NOT EXISTS ",
                schema_sql,
                flags=_re.IGNORECASE,
            )
            try:
                conn.executescript(schema_sql)
                new_tables = {r[0] for r in conn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
                ).fetchall()} - existing_tables
                if new_tables:
                    print(f"[db] Added new tables: {', '.join(sorted(new_tables))}")
                else:
                    print(f"[db] Schema up to date ({len(existing_tables)} tables)")
            except Exception as e:
                print(f"[db] Schema update warning: {e}")

    if seed_file.exists():
        tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").fetchall()
        # Seed tables that are empty (supports adding data to new tables during refinement)
        empty_tables = set()
        for (table_name,) in tables:
            count = conn.execute(f"SELECT COUNT(*) FROM [{table_name}]").fetchone()[0]
            if count == 0:
                empty_tables.add(table_name)

        if empty_tables:
            # Extract and run INSERT statements for empty tables only
            seed_sql = seed_file.read_text(encoding="utf-8")
            import re as _re
            # Replace literal 'null' in VALUES with empty string to avoid NOT NULL violations
            seed_sql = _re.sub(r",null([,)])", r",''\\1", seed_sql, flags=_re.IGNORECASE)
            seed_sql = _re.sub(r"\(null,", "('',", seed_sql, flags=_re.IGNORECASE)
            # Split on INSERT INTO to process per-table
            statements = _re.split(r"(?=INSERT\s+INTO)", seed_sql, flags=_re.IGNORECASE)
            seeded = []
            for stmt in statements:
                stmt = stmt.strip()
                if not stmt:
                    continue
                # Find target table name
                m = _re.match(r"INSERT\s+INTO\s+[`\"]?(\w+)[`\"]?", stmt, _re.IGNORECASE)
                if m and m.group(1) in empty_tables:
                    try:
                        conn.executescript(stmt)
                        seeded.append(m.group(1))
                    except Exception as e:
                        # Retry with OR IGNORE to skip constraint-violating rows
                        try:
                            stmt_ignore = _re.sub(
                                r"INSERT\s+INTO",
                                "INSERT OR IGNORE INTO",
                                stmt,
                                flags=_re.IGNORECASE,
                            )
                            conn.executescript(stmt_ignore)
                            seeded.append(m.group(1))
                            print(f"[db] Seeded {m.group(1)} with OR IGNORE (some rows skipped)")
                        except Exception as e2:
                            print(f"[db] Seed warning for {m.group(1)}: {e2}")
                elif not m:
                    # Non-INSERT preamble (pragmas, etc.) — run unconditionally
                    try:
                        conn.executescript(stmt)
                    except Exception:
                        pass
            if seeded:
                print(f"[db] Seeded new tables: {', '.join(sorted(set(seeded)))}")
            else:
                print(f"[db] No empty tables to seed")
        else:
            print(f"[db] Skipped seed.sql (all tables have data)")

    conn.close()


def _get_tables() -> list[str]:
    conn = _get_db()
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
    ).fetchall()
    conn.close()
    return [r["name"] for r in rows]


def _get_table_schema(table: str) -> list[dict]:
    conn = _get_db()
    rows = conn.execute(f"PRAGMA table_info('{table}')").fetchall()
    conn.close()
    return [{"name": r["name"], "type": r["type"], "pk": bool(r["pk"]), "nullable": not r["notnull"]} for r in rows]


def _get_table_count(table: str) -> int:
    conn = _get_db()
    count = conn.execute(f"SELECT COUNT(*) as c FROM [{table}]").fetchone()["c"]
    conn.close()
    return count


# --- App ---
app = FastAPI(title="TurboUI App Server")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_origin_regex=r"http://(localhost|127\.0\.0\.1)(:\d+)?",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --- API Metadata ---
_api_metadata: list[dict] = []


def _build_metadata():
    """Build API metadata from discovered tables."""
    global _api_metadata
    _api_metadata = []
    tables = _get_tables()
    for table in tables:
        schema = _get_table_schema(table)
        count = _get_table_count(table)
        columns = [col["name"] for col in schema]
        numeric_cols = [col["name"] for col in schema if col["type"].upper() in ("INTEGER", "REAL", "NUMERIC", "FLOAT", "DOUBLE")]

        _api_metadata.append({
            "table": table,
            "description": f"Data table '{table}' with {count} rows",
            "rowCount": count,
            "columns": schema,
            "endpoints": {
                "list": f"/api/data/{table}",
                "byId": f"/api/data/{table}/{{id}}",
                "aggregate": f"/api/data/{table}/aggregate",
                "create": f"/api/data/{table}",
                "update": f"/api/data/{table}/{{id}}",
                "delete": f"/api/data/{table}/{{id}}",
            },
            "queryParams": {
                "list": {
                    "limit": "number (default 100, max 1000)",
                    "offset": "number (default 0)",
                    "sort": f"column name ({', '.join(columns[:5])}...)",
                    "order": "asc|desc (default asc)",
                    "filter": "column:operator:value (operators: eq,ne,gt,lt,gte,lte,like,in)",
                },
                "aggregate": {
                    "groupBy": f"column name ({', '.join(columns[:5])}...)",
                    "metric": f"sum|avg|min|max|count",
                    "column": f"numeric column ({', '.join(numeric_cols[:3])}...)",
                    "filter": "same as list",
                },
            },
        })


@app.get("/api/metadata")
async def get_metadata():
    return {"tables": _api_metadata, "chatEndpoint": "/api/chat"}


# --- Generic Data Endpoints ---
def _parse_filter(filter_str: str) -> tuple[str, list]:
    """Parse 'column:operator:value' into SQL WHERE clause."""
    parts = filter_str.split(":", 2)
    if len(parts) != 3:
        return "", []
    col, op, val = parts
    col_safe = re.sub(r"[^a-zA-Z0-9_]", "", col)
    ops = {"eq": "=", "ne": "!=", "gt": ">", "lt": "<", "gte": ">=", "lte": "<=", "like": "LIKE"}
    if op == "in":
        values = val.split(",")
        placeholders = ",".join("?" * len(values))
        return f"[{col_safe}] IN ({placeholders})", values
    if op not in ops:
        return "", []
    sql_op = ops[op]
    if op == "like":
        val = f"%{val}%"
    return f"[{col_safe}] {sql_op} ?", [val]


@app.get("/api/data/{table}")
async def get_table_data(
    table: str,
    limit: int = Query(100, ge=1, le=1000),
    offset: int = Query(0, ge=0),
    sort: str | None = None,
    order: str = Query("asc", regex="^(asc|desc)$"),
    filter: str | None = None,
):
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    conn = _get_db()
    where_clause = ""
    params: list = []

    if filter:
        filters = filter.split(";")
        conditions = []
        for f in filters:
            clause, vals = _parse_filter(f)
            if clause:
                conditions.append(clause)
                params.extend(vals)
        if conditions:
            where_clause = "WHERE " + " AND ".join(conditions)

    count_sql = f"SELECT COUNT(*) as c FROM [{table}] {where_clause}"
    total = conn.execute(count_sql, params).fetchone()["c"]

    sort_clause = ""
    if sort:
        sort_safe = re.sub(r"[^a-zA-Z0-9_]", "", sort)
        sort_clause = f"ORDER BY [{sort_safe}] {order.upper()}"

    query = f"SELECT * FROM [{table}] {where_clause} {sort_clause} LIMIT ? OFFSET ?"
    rows = conn.execute(query, params + [limit, offset]).fetchall()
    conn.close()

    data = [dict(r) for r in rows]
    return {
        "data": data,
        "total": total,
        "limit": limit,
        "offset": offset,
        "hasMore": (offset + limit) < total,
    }


@app.get("/api/data/{table}/{row_id}")
async def get_table_row(table: str, row_id: int):
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    conn = _get_db()
    row = conn.execute(f"SELECT * FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
    conn.close()

    if not row:
        raise HTTPException(status_code=404, detail="Row not found")
    return dict(row)


@app.get("/api/data/{table}/aggregate")
async def get_table_aggregate(
    table: str,
    groupBy: str | None = None,
    metric: str = Query("count", regex="^(sum|avg|min|max|count)$"),
    column: str | None = None,
    filter: str | None = None,
    limit: int = Query(50, ge=1, le=200),
):
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    where_clause = ""
    params: list = []
    if filter:
        filters = filter.split(";")
        conditions = []
        for f in filters:
            clause, vals = _parse_filter(f)
            if clause:
                conditions.append(clause)
                params.extend(vals)
        if conditions:
            where_clause = "WHERE " + " AND ".join(conditions)

    if metric == "count":
        agg_expr = "COUNT(*)"
    else:
        if not column:
            raise HTTPException(status_code=400, detail=f"'column' required for metric '{metric}'")
        col_safe = re.sub(r"[^a-zA-Z0-9_]", "", column)
        agg_expr = f"{metric.upper()}([{col_safe}])"

    conn = _get_db()
    if groupBy:
        group_safe = re.sub(r"[^a-zA-Z0-9_]", "", groupBy)
        query = f"SELECT [{group_safe}] as _group, {agg_expr} as _value FROM [{table}] {where_clause} GROUP BY [{group_safe}] ORDER BY _value DESC LIMIT ?"
        rows = conn.execute(query, params + [limit]).fetchall()
        conn.close()
        return {"data": [{"group": r["_group"], "value": r["_value"]} for r in rows]}
    else:
        query = f"SELECT {agg_expr} as _value FROM [{table}] {where_clause}"
        row = conn.execute(query, params).fetchone()
        conn.close()
        return {"value": row["_value"]}


# --- Generic CRUD (Create / Update / Delete) Endpoints ---

@app.post("/api/data/{table}")
async def create_row(table: str, request: Request):
    """Insert a new row into a table. Body: JSON object with column:value pairs."""
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    body = await request.json()
    if not body or not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="Request body must be a JSON object")

    # Validate columns exist
    schema = _get_table_schema(table)
    valid_cols = {col["name"] for col in schema}
    cols = [k for k in body.keys() if k in valid_cols]
    if not cols:
        raise HTTPException(status_code=400, detail="No valid columns provided")

    values = [body[c] for c in cols]
    placeholders = ", ".join("?" * len(cols))
    col_list = ", ".join(f"[{c}]" for c in cols)

    conn = _get_db()
    try:
        cursor = conn.execute(f"INSERT INTO [{table}] ({col_list}) VALUES ({placeholders})", values)
        conn.commit()
        row_id = cursor.lastrowid
        row = conn.execute(f"SELECT *, rowid FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
        conn.close()
        return {"data": dict(row), "id": row_id}
    except sqlite3.IntegrityError as e:
        conn.close()
        raise HTTPException(status_code=409, detail=str(e))
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=500, detail=str(e))


@app.put("/api/data/{table}/{row_id}")
async def update_row(table: str, row_id: int, request: Request):
    """Update an existing row. Body: JSON object with column:value pairs to update."""
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    body = await request.json()
    if not body or not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="Request body must be a JSON object")

    schema = _get_table_schema(table)
    valid_cols = {col["name"] for col in schema}
    cols = [k for k in body.keys() if k in valid_cols]
    if not cols:
        raise HTTPException(status_code=400, detail="No valid columns provided")

    set_clause = ", ".join(f"[{c}] = ?" for c in cols)
    values = [body[c] for c in cols]

    conn = _get_db()
    # Check row exists
    existing = conn.execute(f"SELECT rowid FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
    if not existing:
        conn.close()
        raise HTTPException(status_code=404, detail="Row not found")

    try:
        conn.execute(f"UPDATE [{table}] SET {set_clause} WHERE rowid = ?", values + [row_id])
        conn.commit()
        row = conn.execute(f"SELECT *, rowid FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
        conn.close()
        return {"data": dict(row)}
    except sqlite3.IntegrityError as e:
        conn.close()
        raise HTTPException(status_code=409, detail=str(e))
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=500, detail=str(e))


@app.delete("/api/data/{table}/{row_id}")
async def delete_row(table: str, row_id: int):
    """Delete a row by rowid."""
    tables = _get_tables()
    if table not in tables:
        raise HTTPException(status_code=404, detail=f"Table '{table}' not found")

    conn = _get_db()
    existing = conn.execute(f"SELECT rowid FROM [{table}] WHERE rowid = ?", [row_id]).fetchone()
    if not existing:
        conn.close()
        raise HTTPException(status_code=404, detail="Row not found")

    conn.execute(f"DELETE FROM [{table}] WHERE rowid = ?", [row_id])
    conn.commit()
    conn.close()
    return {"deleted": True, "id": row_id}


# --- Chat Endpoint ---
class ChatMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    responseFormat: str = "auto"
    context: dict | None = None


def _build_chat_system_prompt() -> str:
    """Build a system prompt with API metadata awareness."""
    tables_info = []
    for meta in _api_metadata:
        cols = ", ".join(f"{c['name']} ({c['type']})" for c in meta["columns"])
        tables_info.append(
            f"- **{meta['table']}** ({meta['rowCount']} rows): {cols}\n"
            f"  Endpoints: GET {meta['endpoints']['list']}?limit=N&offset=N&sort=COL&order=asc|desc&filter=COL:OP:VAL\n"
            f"             GET {meta['endpoints']['aggregate']}?groupBy=COL&metric=sum|avg|min|max|count&column=COL"
        )
    tables_section = "\n".join(tables_info)

    return (
        "You are an expert data analyst for this application.\n\n"
        "## Available Data (via REST API)\n"
        f"{tables_section}\n\n"
        "## Filter syntax\n"
        "filter=column:operator:value  (operators: eq, ne, gt, lt, gte, lte, like, in)\n"
        "Multiple filters: filter=col1:eq:val1;col2:gt:val2\n\n"
        "## Response format rules\n"
        "- If the answer is best shown as a chart, wrap it in ```chart\\n{json}\\n``` "
        "where json is: {\"type\": \"bar\"|\"line\"|\"donut\"|\"scatter\", \"title\": \"...\", \"data\": [...], \"xKey\": \"fieldName\", \"yKeys\": [\"fieldName1\"]}\n"
        "- If the answer is best shown as a geographic map, wrap it in ```map\\n{json}\\n``` "
        "where json is: {\"mapType\": \"world\"|\"usa\", \"title\": \"...\", \"data\": [{\"id\": \"ISO2_CODE\", \"value\": number, \"label\": \"...\"}], "
        "\"valueLabel\": \"field description\", \"colorScheme\": \"blue\"|\"green\"|\"red\"|\"purple\"}\n"
        "  - Use mapType \"world\" for country-level data (id = ISO 3166-1 alpha-2 code like \"US\", \"DE\", \"CN\")\n"
        "  - Use mapType \"usa\" only if data has US state-level granularity (id = state FIPS or postal code)\n"
        "  - Use a map when the user asks to \"show on a map\", \"visualize geographically\", or when the data has a clear geographic dimension and the user asks for a spatial view\n"
        "- If best as a table, wrap it in ```table\\n[{...}, ...]\\n```\n"
        "- Otherwise respond in plain text with markdown formatting.\n"
        "- Use the actual data from the database to compute your answers.\n"
        "- When asked to show data, query it and include real values — never make up numbers.\n"
        "- For aggregations, use the aggregate endpoint mentally to describe the correct values.\n"
    )


def _parse_llm_response(text: str) -> dict[str, Any]:
    """Parse LLM response for embedded chart/table/map blocks."""
    map_match = re.search(r"```map\s*\n([\s\S]*?)\n```", text)
    if map_match:
        try:
            data = json.loads(map_match.group(1))
            clean = text[:map_match.start()].strip() + "\n\n" + text[map_match.end():].strip()
            return {"response": clean.strip(), "type": "map", "data": data}
        except json.JSONDecodeError:
            pass

    chart_match = re.search(r"```chart\s*\n([\s\S]*?)\n```", text)
    if chart_match:
        try:
            data = json.loads(chart_match.group(1))
            clean = text[:chart_match.start()].strip() + "\n\n" + text[chart_match.end():].strip()
            return {"response": clean.strip(), "type": "chart", "data": data}
        except json.JSONDecodeError:
            pass

    table_match = re.search(r"```table\s*\n([\s\S]*?)\n```", text)
    if table_match:
        try:
            data = json.loads(table_match.group(1))
            clean = text[:table_match.start()].strip() + "\n\n" + text[table_match.end():].strip()
            return {"response": clean.strip(), "type": "table", "data": data}
        except json.JSONDecodeError:
            pass

    try:
        data = json.loads(text)
        if isinstance(data, dict) and "type" in data:
            return {"response": text, "type": "chart", "data": data}
        if isinstance(data, list):
            return {"response": text, "type": "table", "data": data}
    except json.JSONDecodeError:
        pass

    return {"response": text, "type": "text", "data": None}


@app.post("/api/chat")
async def chat(request: ChatRequest):
    import asyncio
    from openai import AsyncOpenAI
    global llm_client, http_client

    if not llm_client:
        raise HTTPException(status_code=503, detail="LLM not configured — check .env credentials")

    try:
        system_prompt = _build_chat_system_prompt()
        if request.context:
            system_prompt += f"\n\nAdditional context: {json.dumps(request.context)}"

        if request.responseFormat == "chart":
            system_prompt += "\n\nIMPORTANT: Respond with a chart visualization using the ```chart format."
        elif request.responseFormat == "table":
            system_prompt += "\n\nIMPORTANT: Respond with tabular data using the ```table format."

        # Inject sample data into system prompt for accurate answers
        sample_data = {}
        conn = _get_db()
        for meta in _api_metadata[:5]:
            rows = conn.execute(f"SELECT * FROM [{meta['table']}] LIMIT 10").fetchall()
            sample_data[meta["table"]] = [dict(r) for r in rows]
        conn.close()
        system_prompt += f"\n\n## Sample data (first 10 rows per table)\n```json\n{json.dumps(sample_data, default=str, indent=2)}\n```"

        messages = [{"role": "system", "content": system_prompt}]
        # Keep only last 20 messages to avoid exceeding token limits
        recent = request.messages[-20:] if len(request.messages) > 20 else request.messages
        messages.extend([{"role": m.role, "content": m.content} for m in recent])

        last_err = None
        for _attempt in range(3):
            try:
                completion = await llm_client.chat.completions.create(
                    model=LITELLM_MODEL,
                    messages=messages,
                    temperature=0.3,
                )
                text = completion.choices[0].message.content
                return _parse_llm_response(text)
            except Exception as attempt_err:
                last_err = attempt_err
                print(f"[chat] attempt {_attempt+1} failed: {type(attempt_err).__name__}: {attempt_err}", flush=True)
                if _attempt < 2:
                    # Recreate HTTP client on connection errors (stale pool, SSL tear-down)
                    try:
                        await http_client.aclose()
                    except Exception:
                        pass
                    http_client = _make_http_client()
                    llm_client = AsyncOpenAI(
                        api_key=LITELLM_API_KEY,
                        base_url=LITELLM_API_BASE.rstrip("/") + "/v1",
                        http_client=http_client,
                        timeout=LITELLM_TIMEOUT,
                    )
                    await asyncio.sleep(2 * (_attempt + 1))
        raise HTTPException(status_code=500, detail=f"LLM call failed after 3 attempts: {last_err}")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# --- File upload endpoints (for Excel/PDF chat) ---
@app.post("/api/ingest/excel")
async def ingest_excel(file: UploadFile = File(...)):
    try:
        import openpyxl
        suffix = Path(file.filename or "upload.xlsx").suffix
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            content = await file.read()
            tmp.write(content)
            tmp_path = tmp.name

        wb = openpyxl.load_workbook(tmp_path, read_only=True, data_only=True)
        sheets = []
        for sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            rows_raw = list(ws.iter_rows(values_only=True))
            if not rows_raw:
                continue
            headers = [str(h) if h else f"col_{i}" for i, h in enumerate(rows_raw[0])]
            data_rows = [dict(zip(headers, row)) for row in rows_raw[1:]]
            schema = [{"name": h, "type": _detect_col_type([r.get(h) for r in data_rows[:50]])} for h in headers]
            sheets.append({
                "name": sheet_name,
                "schema": schema,
                "rows": data_rows[:100],
                "totalRows": len(data_rows),
                "sampleRows": data_rows[:10],
            })
        wb.close()
        os.unlink(tmp_path)
        return {"sheets": sheets}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/ingest/pdf")
async def ingest_pdf(file: UploadFile = File(...)):
    try:
        import fitz
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
            content = await file.read()
            tmp.write(content)
            tmp_path = tmp.name

        doc = fitz.open(tmp_path)
        chunks = [page.get_text() for page in doc]
        full_text = "\n".join(chunks)
        title = doc.metadata.get("title", "") if doc.metadata else ""
        page_count = len(doc)
        doc.close()
        os.unlink(tmp_path)
        return {"pages": page_count, "text": full_text, "chunks": chunks, "metadata": {"title": title, "pages": page_count}}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def _detect_col_type(values: list) -> str:
    non_empty = [v for v in values if v is not None and str(v).strip() != ""]
    if not non_empty:
        return "TEXT"
    numeric_count = sum(1 for v in non_empty if _is_numeric(v))
    if numeric_count == len(non_empty):
        return "REAL" if any("." in str(v) for v in non_empty) else "INTEGER"
    return "TEXT"


def _is_numeric(v) -> bool:
    try:
        float(v)
        return True
    except (ValueError, TypeError):
        return False


# --- Health ---
@app.get("/health")
async def health():
    tables = _get_tables()
    return {"status": "ok", "tables": len(tables), "database": DB_PATH}


# --- Startup ---
@app.on_event("startup")
async def startup():
    _init_db()
    _build_metadata()
    tables = _get_tables()
    print(f"\n  TurboUI App Server running on port {API_PORT}")
    print(f"  Database: {DB_PATH} ({len(tables)} tables)")
    print(f"  Endpoints:")
    for meta in _api_metadata:
        print(f"    GET /api/data/{meta['table']}  ({meta['rowCount']} rows)")
    print(f"    GET  /api/metadata        — API catalog")
    print(f"    POST /api/chat            — AI data chat")
    print(f"    GET  /health              — Health check\n")


# --- Static file serving (production) ---
dist_dir = Path("dist")
if dist_dir.exists():
    app.mount("/assets", StaticFiles(directory=str(dist_dir / "assets")), name="assets")

    @app.get("/{full_path:path}")
    async def serve_spa(full_path: str):
        file_path = dist_dir / full_path
        if file_path.exists() and file_path.is_file():
            return FileResponse(str(file_path))
        return FileResponse(str(dist_dir / "index.html"))


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=API_PORT)
