"""
SDK-native web-app builder (Phase 3).

Replaces the legacy CrewOrchestrator LLM pipeline with a persistent ClaudeSDKClient
that writes files directly into the project dir, then reuses uigen_agent's tested,
deterministic scaffold/bundle/link/serve/QA machinery (no LLM inside it) to finalize
and run the app. Self-heal is agent-driven (the same open session), so it needs no
LiteLLM — works with provider=local/bedrock/litellm alike.

Entry point:  await generate_project_sdk(prompt, project_name=None, provider=None, progress=None)
"""

from __future__ import annotations

import asyncio
import re
from pathlib import Path

from claude_agent_sdk import (
    ClaudeSDKClient, AssistantMessage, TextBlock, ThinkingBlock,
    ToolUseBlock, ToolResultBlock, UserMessage, ResultMessage,
)

from . import uigen_agent as ug
from . import agent_runtime
from . import projects as project_store
from .turboui_mcp import ProjectContext

# Source file extensions the agent authors (read back from disk after generation).
_SRC_EXT = (".tsx", ".ts", ".css", ".sql", ".html", ".json", ".js", ".txt", ".md")

_SEED_APP_TSX = """\
import { Routes, Route } from 'react-router-dom';

export default function App() {
  return (
    <Routes>
      <Route path="/" element={
        <div style={{ padding: 48, fontFamily: 'Inter, sans-serif', color: '#64748b', textAlign: 'center' }}>
          <div style={{ fontSize: 15 }}>Your app will appear here as we build it together.</div>
        </div>
      } />
    </Routes>
  );
}
"""

_SEED_TYPES_TS = "// Generated by the data-architect. Interfaces mirror api/schema.sql tables.\nexport {};\n"

# Ambient shim so `tsc_check` resolves the design system the SAME way Vite does (via the
# vite alias mobility-global-ds -> DS/src/index.ts). Without this the agent's tsc self-heal
# chases phantom TS2307 "Cannot find module 'mobility-global-ds'" errors. Real types come
# from Vite at runtime; this shim only keeps tsc honest during the build.
_DS_TYPE_SHIM = """\
// Auto-seeded type shim for the mobility-global-ds design system.
// Vite resolves the real module via an alias; this keeps `tsc --noEmit` resolving too.
declare module 'mobility-global-ds' {
  import * as React from 'react';
  type AnyProps = Record<string, any>;
  export const Button: React.FC<AnyProps>;
  export const Input: React.FC<AnyProps>;
  export const Badge: React.FC<AnyProps>;
  export const Card: React.FC<AnyProps>;
  export const KpiCard: React.FC<AnyProps>;
  export const Header: React.FC<AnyProps>;
  export const Sidebar: React.FC<AnyProps>;
  export const Footer: React.FC<AnyProps>;
  export const Modal: React.FC<AnyProps>;
  export const Alert: React.FC<AnyProps>;
  export const DataTable: React.FC<AnyProps>;
  export const Tabs: React.FC<AnyProps>;
  export const Dropdown: React.FC<AnyProps>;
  export const SearchBar: React.FC<AnyProps>;
  export const Pagination: React.FC<AnyProps>;
  export const ProgressBar: React.FC<AnyProps>;
  export const Avatar: React.FC<AnyProps>;
  export const AvatarGroup: React.FC<AnyProps>;
  export const Tooltip: React.FC<AnyProps>;
  export const Breadcrumb: React.FC<AnyProps>;
  const _default: any;
  export default _default;
  export const colors: any, usage: any, spacing: any, radius: any,
    shadow: any, components: any, typography: any;
}
"""


def _useapi_hook_source() -> str:
    """The real useApi hook the app runs against (bundled at finalize by _bundle_api_server).
    Seeded early so the agent's pages typecheck against it during the build."""
    tmpl = Path(__file__).parent / "services_engineer" / "templates" / "useApi.hook.ts"
    try:
        return tmpl.read_text(encoding="utf-8")
    except Exception:
        return "export function useApi<T=any>(_t: string): { data: T[]; loading: boolean; error: string|null } {\n  return { data: [], loading: false, error: null };\n}\nexport function apiAggregate(..._a: any[]): any { return null; }\n"


def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9-]", "-", (name or "app").lower()).strip("-") or "app"


def _builder_prompt(user_prompt: str) -> str:
    augmented = ug._augment_prompt(user_prompt, backend_type="python")
    return f"""You are the TurboUIGen web-app builder. Build a complete, working React app in the CURRENT directory by WRITING files with your tools.

A minimal skeleton already exists: package.json, tsconfig.json, src/main.tsx (wraps <App/> in a BrowserRouter with the correct basename), a placeholder src/App.tsx, and src/index.css. node_modules is linked. DO NOT create or edit these managed files: vite.config.ts, package.json, tsconfig.json, src/main.tsx, api/app_server.py, api/.env, src/hooks/useApi.ts — they are provided/managed by the platform.

## What to build
{augmented}

## Required deliverables (write these exact paths)
1. api/schema.sql — SQLite CREATE TABLE statements. snake_case table & column names. Every main table >= 5 columns.
2. api/seed.sql — realistic INSERT data, >= 50 rows for each main table (no 'test'/'lorem'/999 placeholders). Multi-row INSERT syntax.
3. src/types.ts — one PascalCase interface per table, mirroring the columns.
4. src/App.tsx — replace the placeholder: import your pages and define <Routes>/<Route> for every page. Include a Sidebar/Header from mobility-global-ds for navigation.
5. src/pages/*.tsx — one component per page. Real content, no empty stubs.
6. src/components/*.tsx — shared components (charts/maps) as needed.

## Rules (also in your system prompt)
- Use the mobility-global-ds design system for standard UI. Charts/maps: D3 only.
- Fetch data with: import {{ useApi, apiAggregate }} from '../hooks/useApi'  →  GET /api/data/{{table}}. Fields are snake_case. Never import from '../data'.
- For charts, maps, exports, or AI chat, USE YOUR SKILLS (e.g. turbo-uigen:d3-charts, turbo-uigen:usa-map, turbo-uigen:ai-chat) — read their reference implementations rather than writing D3 from scratch.
- You may delegate to your subagents (ux-architect, data-architect, visual-design-engineer, ai-genai-engineer) via the Task tool.

## Workflow
1. Decide the app architecture (pages + navigation + data entities). You may delegate this to the ux-architect subagent.
2. Write api/schema.sql, api/seed.sql, src/types.ts (delegate to data-architect if useful). Validate with mcp__turboui__validate_data_layer and fix issues.
3. Write src/App.tsx and every src/pages/*.tsx and needed src/components/*.tsx.
4. Run mcp__turboui__tsc_check and fix reported errors (only the reported files). Repeat until clean or 3 rounds.
5. Stop. Do not start servers or run QA — the platform does that.

## Talking to the user (non-technical audience)
The person reading along is NOT a developer, and they see your narration as you work.
As you build, briefly explain what you're doing in warm, everyday language — talk about the
app and its features (its pages, its data, its charts), not about files, code, SQL, or tools.
A sentence before each meaningful step is plenty; keep it natural and conversational, like a
designer thinking out loud with a client. Don't announce tool or file operations.
"""


def _read_project_files(project_dir: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    for fp in project_dir.rglob("*"):
        if not fp.is_file() or fp.suffix not in _SRC_EXT:
            continue
        rel = fp.relative_to(project_dir).as_posix()
        if rel.startswith("node_modules/") or rel.startswith(".") or "/node_modules/" in rel:
            continue
        try:
            files[rel] = fp.read_text(encoding="utf-8")
        except Exception:
            pass
    return files


async def _run_agent(client: ClaudeSDKClient, prompt: str, progress) -> dict:
    """Send one turn, stream progress, return {session_id, cost, tools:[...]}."""
    await client.query(prompt)
    info = {"session_id": None, "cost": 0.0, "tools": []}
    async for msg in client.receive_response():
        if isinstance(msg, AssistantMessage):
            for b in msg.content:
                if isinstance(b, TextBlock) and b.text.strip():
                    progress(f"agent:{b.text.strip()[:120]}")
                elif isinstance(b, ToolUseBlock):
                    info["tools"].append(b.name)
                    tgt = (b.input or {}).get("file_path") or (b.input or {}).get("subagent_type") or ""
                    progress(f"tool:{b.name} {str(tgt)[:60]}")
        elif isinstance(msg, ResultMessage):
            # origin guard: only capture the human turn's session id
            origin = getattr(msg, "origin", None)
            if origin is None or (isinstance(origin, dict) and origin.get("kind") == "human"):
                info["session_id"] = msg.session_id
                info["cost"] = getattr(msg, "total_cost_usd", 0.0) or 0.0
    return info


def _finalize_and_serve(project_name: str, project_dir: Path, port: int, api_port: int, progress):
    """Reuse the legacy deterministic pipeline (NO LLM) to bundle, link, serve, and QA."""
    files = _read_project_files(project_dir)
    if "api/schema.sql" not in files and "schema.sql" not in files:
        raise RuntimeError("Agent did not produce a schema.sql — cannot finalize the app.")

    files = ug._ensure_boilerplate(files, project_name)
    files = ug._bundle_api_server(files, backend_type="python")
    if "api/.env" in files and api_port:
        files["api/.env"] = re.sub(r"API_PORT=\d+", f"API_PORT={api_port}", files["api/.env"])
    files = ug.run_all_postprocessors(files, project_dir=project_dir, project_name=project_name,
                                      port=port, api_port=api_port or 0)
    files = ug._ensure_required_components(files)

    progress("write")
    ug.kill_server(project_name)
    ug._write_files(project_dir, files)

    progress("install")
    ok, log = ug._ensure_shared_nm_once()
    if not ok:
        raise RuntimeError(f"Shared npm install failed:\n{log[-1500:]}")
    deps = ug._get_project_deps(project_dir)
    for pkg in ug._scan_imports_from_files(project_dir):
        deps.setdefault(pkg, "latest")
    ok2, _ = ug._link_shared_nm(project_dir, deps, progress=progress)
    if not ok2:
        ok3, log3 = ug._npm_install(project_dir)
        if not ok3:
            raise RuntimeError(f"npm install failed:\n{log3[-1500:]}")
    ug._link_ds_into_project(project_dir)

    progress("start")
    has_api = (project_dir / "api" / "app_server.py").exists() or (project_dir / "api" / "schema.sql").exists()
    if has_api:
        api_proc = ug._start_api_server(project_dir, api_port=api_port)
        if api_proc:
            ug._api_servers[project_name] = api_proc
            ug._wait_for_api(api_port, timeout=20)
    proc = ug._start_vite(project_dir, port)
    ug._dev_servers[project_name] = proc
    if not ug.wait_for_port(port, timeout=60):
        raise RuntimeError("Vite dev server did not start in time")

    deps_meta = project_dir / "node_modules" / ".vite" / "deps" / "_metadata.json"
    import time
    deadline = time.time() + 30
    while time.time() < deadline and not deps_meta.exists():
        time.sleep(1)

    progress("qa")
    return ug.run_qa(project_name, port, project_dir)


# Minimal placeholder data layer so the API server can boot before Claude writes the real one.
_PLACEHOLDER_SCHEMA = "CREATE TABLE app_info (\n  id INTEGER PRIMARY KEY,\n  name TEXT\n);\n"
_PLACEHOLDER_SEED = "INSERT INTO app_info (id, name) VALUES (1, 'starter');\n"

_PREPARED: set[str] = set()   # slugs whose workspace is set up + serving this process


def _has_real_app(project_dir: Path) -> bool:
    """True if this project already contains a built app (not just the seeded skeleton)."""
    for d in ("pages", "components"):
        p = project_dir / "src" / d
        if p.exists() and any(p.glob("*.tsx")):
            return True
    app = project_dir / "src" / "App.tsx"
    if app.exists():
        try:
            if len(app.read_text(encoding="utf-8").splitlines()) > 20:  # >placeholder
                return True
        except OSError:
            pass
    return False


def _ensure_serving(slug: str, project_dir: Path, port: int, api_port: int, progress) -> None:
    """Ensure node_modules are linked and Vite/API are running — WITHOUT touching files."""
    ug._ensure_shared_nm_once()
    try:
        ug._link_shared_nm(project_dir, ug._get_project_deps(project_dir), progress=progress)
        ug._link_ds_into_project(project_dir)
    except Exception:
        pass
    if slug not in ug._api_servers and (project_dir / "api" / "schema.sql").exists():
        proc = ug._start_api_server(project_dir, api_port=api_port)
        if proc:
            ug._api_servers[slug] = proc
            ug._wait_for_api(api_port, timeout=20)
    if slug not in ug._dev_servers or not ug.wait_for_port(port, timeout=2):
        proc = ug._start_vite(project_dir, port)
        ug._dev_servers[slug] = proc
        ug.wait_for_port(port, timeout=60)


def prepare_workspace(slug: str, port: int, api_port: int, progress) -> Path:
    """One-time per process: make the project live-serving so Claude can work in it.

    - EXISTING built app (reopened): NEVER wipe — just relink + (re)start its servers.
    - Fresh/skeleton project: scaffold a placeholder app + live Vite/API (HMR from turn one).
    """
    project_dir = project_store.dir_for_key(slug)

    # Guard against data loss: reopening a built project must not re-seed/wipe it.
    if _has_real_app(project_dir):
        ug.registry_upsert(slug, port=port, type="react", source="prompt")
        progress("crew:Reopening your app…")
        _ensure_serving(slug, project_dir, port, api_port, progress)
        _PREPARED.add(slug)
        return project_dir

    ug.registry_upsert(slug, port=port, type="react", source="prompt")
    files = ug._ensure_boilerplate({}, slug)
    files["src/App.tsx"] = _SEED_APP_TSX
    files["src/types.ts"] = _SEED_TYPES_TS
    files["src/hooks/useApi.ts"] = _useapi_hook_source()
    files["src/types/mobility-global-ds.d.ts"] = _DS_TYPE_SHIM
    files["api/schema.sql"] = _PLACEHOLDER_SCHEMA
    files["api/seed.sql"] = _PLACEHOLDER_SEED

    files = ug._bundle_api_server(files, backend_type="python")
    if "api/.env" in files:
        files["api/.env"] = re.sub(r"API_PORT=\d+", f"API_PORT={api_port}", files["api/.env"])
    # vite.config: DS alias + react dedupe, then the server block (port + /api proxy + base path)
    from . import postprocessors as pp
    files = pp._patch_vite_for_ds(files, project_dir)
    files = pp._inject_api_proxy(files, slug, port, api_port)

    progress("crew:Preparing your workspace…")
    ug.kill_server(slug)
    ug._write_files(project_dir, files)
    ok, log = ug._ensure_shared_nm_once()
    if not ok:
        raise RuntimeError(f"Shared npm install failed:\n{log[-1500:]}")
    ug._link_shared_nm(project_dir, ug._get_project_deps(project_dir), progress=progress)
    ug._link_ds_into_project(project_dir)

    api_proc = ug._start_api_server(project_dir, api_port=api_port)
    if api_proc:
        ug._api_servers[slug] = api_proc
        ug._wait_for_api(api_port, timeout=20)
    proc = ug._start_vite(project_dir, port)
    ug._dev_servers[slug] = proc
    ug.wait_for_port(port, timeout=60)
    _PREPARED.add(slug)
    return project_dir


def sync_workspace(slug: str, project_dir: Path, port: int, api_port: int, progress) -> None:
    """Light per-turn sync after Claude edits files: install any new deps and restart the
    API if the data layer changed. Vite HMR already handles the frontend live."""
    # Mark the project as a real, runnable app in the registry once Claude has actually
    # built something (pages/components exist beyond the seeded skeleton). Without this the
    # sidebar treats it as "no app generated yet" and hides the Start/Preview/refine controls.
    has_real_app = any((project_dir / "src" / d).exists() and any((project_dir / "src" / d).glob("*.tsx"))
                       for d in ("pages", "components"))
    if has_real_app:
        ug.registry_upsert(
            slug, hasApp=True, type="react", source="prompt",
            sourceLabel="Chat", title=slug.replace("-", " ").title(), port=port,
        )

    # install packages Claude may have imported that aren't linked yet
    try:
        deps = ug._get_project_deps(project_dir)
        for pkg in ug._scan_imports_from_files(project_dir):
            deps.setdefault(pkg, "latest")
        ug._link_shared_nm(project_dir, deps, progress=progress)
    except Exception:
        pass
    # restart the API so a rewritten schema.sql/seed.sql is loaded into data.db
    schema = project_dir / "api" / "schema.sql"
    if schema.exists():
        try:
            files = _read_project_files(project_dir)
            files = ug._bundle_api_server(files, backend_type="python")
            if "api/.env" in files:
                files["api/.env"] = re.sub(r"API_PORT=\d+", f"API_PORT={api_port}", files["api/.env"])
            # write back only the managed api files (avoid clobbering Claude's src)
            for k in ("api/app_server.py", "api/.env", "api/requirements.txt", "api/seed.sql", "api/schema.sql"):
                if k in files:
                    p = project_dir / k
                    p.parent.mkdir(parents=True, exist_ok=True)
                    p.write_text(files[k], encoding="utf-8")
            # drop the stale db so the server rebuilds it from the new schema/seed
            for db in ("data.db", "app.db", "api/data.db", "api/app.db"):
                dbp = project_dir / db
                if dbp.exists():
                    dbp.unlink()
            progress("crew:Refreshing your app's data…")
            ug._stop_api_server(slug) if hasattr(ug, "_stop_api_server") else None
            proc = ug._start_api_server(project_dir, api_port=api_port)
            if proc:
                ug._api_servers[slug] = proc
                ug._wait_for_api(api_port, timeout=20)
        except Exception:
            pass


def assign_ports(slug: str) -> tuple[int, int]:
    """Assign (or reuse) the vite + api ports for a slug and persist them."""
    port = ug._dev_ports.get(slug) or ug._next_port()
    ug._dev_ports[slug] = port
    api_port = ug._api_ports.get(slug) or ug._next_api_port()
    ug._api_ports[slug] = api_port
    ug._save_ports()
    return port, api_port


def seed_skeleton(slug: str, prompt: str, port: int, api_port: int, progress) -> Path:
    """Write a minimal compiling skeleton and link node_modules + DS. Returns project_dir."""
    project_dir = project_store.dir_for_key(slug)
    ug.registry_upsert(slug, port=port, type="react", source="prompt", prompt=prompt[:2000])
    progress("crew:Preparing project skeleton…")
    seed = ug._ensure_boilerplate({}, slug)
    seed.setdefault("src/App.tsx", _SEED_APP_TSX)
    seed.setdefault("src/types.ts", _SEED_TYPES_TS)
    seed["src/hooks/useApi.ts"] = _useapi_hook_source()
    seed["src/types/mobility-global-ds.d.ts"] = _DS_TYPE_SHIM
    ug.kill_server(slug)
    ug._write_files(project_dir, seed)
    ok, log = ug._ensure_shared_nm_once()
    if not ok:
        raise RuntimeError(f"Shared npm install failed:\n{log[-1500:]}")
    ug._link_shared_nm(project_dir, ug._get_project_deps(project_dir), progress=progress)
    ug._link_ds_into_project(project_dir)
    return project_dir


def _heal_prompt(qa_report) -> str:
    errs = [f for f in qa_report.findings if f.severity == "error"]
    lines = [f"- [{f.category}] {f.file}: {f.message}" for f in errs[:20]]
    return (
        "The app is running but QA found errors. Fix ONLY the files named below, then stop. "
        "Read api/schema.sql first — API fields are snake_case. Do not touch managed files.\n\n"
        + "\n".join(lines)
    )


async def generate_project_sdk(prompt: str, project_name: str | None = None,
                               provider: str | None = None, progress=None,
                               heal_rounds: int = 2) -> dict:
    """Generate a web app with the SDK-native builder. Returns the same shape as generate_project."""
    def _p(s):
        if progress:
            progress(s)

    slug = _slugify(project_name or " ".join(prompt.split()[:4]))
    port, api_port = assign_ports(slug)

    # ── 1. Seed a minimal skeleton so node_modules links & the agent has a project ──
    project_dir = seed_skeleton(slug, prompt, port, api_port, _p)

    # ── 2. Run the builder agent (writes real files into project_dir) ──
    _p("crew:Building app with the SDK agent…")
    ctx = ProjectContext(project_name=slug, project_dir=project_dir, port=port, api_port=api_port)
    opts = agent_runtime.build_options(ctx, provider=provider)
    async with ClaudeSDKClient(opts) as client:
        run = await _run_agent(client, _builder_prompt(prompt), _p)
        _p(f"crew:Agent finished ({len(run['tools'])} tool calls, ${run['cost']:.2f})")

        # ── 3. Deterministic finalize + serve + QA (reused legacy pipeline) ──
        qa = await asyncio.to_thread(_finalize_and_serve, slug, project_dir, port, api_port, _p)

        # ── 4. Agent-driven self-heal (bounded) ──
        rounds = 0
        while not qa.passed and qa.pages_fail and rounds < heal_rounds:
            rounds += 1
            _p(f"crew:QA failed (score {qa.score}) — agent heal round {rounds}…")
            await _run_agent(client, _heal_prompt(qa), _p)
            await asyncio.sleep(3)  # let Vite HMR recompile the edited files
            qa = await asyncio.to_thread(ug.run_qa, slug, port, project_dir)

    _p("ready")
    files = _read_project_files(project_dir)
    return {
        "projectName": slug,
        "title": slug.replace("-", " ").title(),
        "description": "",
        "port": port,
        "url": f"/app/{slug}/",
        "files": list(files.keys()),
        "qa": qa.to_dict(),
        "sessionId": run.get("session_id"),
        "engine": "sdk",
    }
